# Test configuration for TEMA vs SMA Crossover strategy
name: test_tema_sma_crossover
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# TEMA vs SMA crossover strategy
strategy:
  tema_sma_crossover:
    params:
      tema_period: 10
      sma_period: 20

# Run with: python main.py --config config/indicators/crossover/test_tema_sma_crossover.yaml --signal-generation --bars 100

# Expected behavior:
# - TEMA > SMA: BUY signal (1)
# - TEMA < SMA: SELL signal (-1)
# - TEMA = SMA: No signal (0)

# TEMA (Triple Exponential MA) has minimal lag
# Applies EMA calculation three times for ultra-responsiveness