# Test configuration for DEMA Crossover strategy
name: test_dema_crossover
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# DEMA fast/slow crossover strategy
strategy:
  dema_crossover:
    params:
      fast_dema_period: 10
      slow_dema_period: 20

# Run with: python main.py --config config/indicators/crossover/test_dema_crossover.yaml --signal-generation --bars 100

# Expected behavior:
# - Fast DEMA > Slow DEMA: BUY signal (1)
# - Fast DEMA < Slow DEMA: SELL signal (-1)
# - Fast DEMA = Slow DEMA: No signal (0)

# Double EMA crossover - both lines are highly responsive
# Good for catching trend changes early with less lag