# Test configuration for Stochastic Crossover strategy
name: test_stochastic_crossover
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Stochastic %K vs %D crossover strategy
strategy:
  stochastic_crossover:
    params:
      k_period: 14
      d_period: 3

# Run with: python main.py --config config/indicators/crossover/test_stochastic_crossover.yaml --signal-generation --bars 100

# Expected behavior:
# - %K > %D: BUY signal (1)
# - %K < %D: SELL signal (-1)
# - %K = %D: No signal (0)

# %K is the fast stochastic line
# %D is the slow stochastic line (3-period SMA of %K)
# Crossovers indicate momentum shifts