# Test configuration for SMA Crossover strategy
name: test_sma_crossover
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  sma_crossover:
    params:
      fast_period: 10
      slow_period: 20

# Run with: python main.py --config config/indicators/test_sma_crossover.yaml --signal-generation --bars 100

# Expected behavior:
# - Fast SMA > Slow SMA: BUY signal (1)
# - Fast SMA < Slow SMA: SELL signal (-1)
# - Fast SMA = Slow SMA: No signal (0)

# The signal is sustained (not just on crossover)
# Signal changes only when relationship changes