# Test configuration for MA Crossover strategy
name: test_ma_crossover
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Generic moving average crossover strategy
strategy:
  ma_crossover:
    params:
      fast_period: 10
      slow_period: 20
      ma_type: sma  # sma or ema

# Run with: python main.py --config config/indicators/crossover/test_ma_crossover.yaml --signal-generation --bars 100
