# Test configuration for Ichimoku Cloud Position strategy
name: test_ichimoku_cloud_position
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Ichimoku cloud position strategy
strategy:
  ichimoku_cloud_position:
    params:
      conversion_period: 9
      base_period: 26

# Run with: python main.py --config config/indicators/crossover/test_ichimoku_cloud_position.yaml --signal-generation --bars 100

# Expected behavior:
# - Price > Cloud Top: BUY signal (1) - bullish
# - Price < Cloud Bottom: SELL signal (-1) - bearish
# - Price inside Cloud: No signal (0) - neutral/uncertain

# The cloud (Kumo) is formed by Senkou Span A and B
# Acts as dynamic support/resistance
# Cloud thickness indicates market volatility