# Swing Pivot Bounce Strategy - 15 Minute Timeframe
# Mean reversion strategy that trades bounces off dynamic support/resistance levels
name: swing_pivot_bounce_15m
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features - adjusted for 15m timeframe
feature_config:
  support_resistance_20:  # Same lookback period
    type: support_resistance
    lookback: 20         # 20 bars = 5 hours on 15m
    min_touches: 2

# Strategy configuration
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 20           # Support/Resistance lookback period
      min_touches: 2          # Minimum touches to validate level
      bounce_threshold: 0.002 # 0.2% proximity for bounce detection
      exit_threshold: 0.001   # 0.1% from midpoint to exit position