# Swing Pivot Bounce Strategy - Win Rate Optimization
# Test parameters to improve win rate while maintaining 2-5 trades/day
name: swing_pivot_bounce_winrate_optimize
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Base configuration
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 30
      min_touches: 3
      bounce_threshold: 0.004
      exit_threshold: 0.002

# Parameter space focused on win rate improvement
parameter_space:
  strategies:
    - type: swing_pivot_bounce
      param_overrides:
        # Moderate lookbacks for good trade frequency
        sr_period: [20, 25, 30, 35, 40]
        
        # Standard touch requirements
        min_touches: [2, 3, 4]
        
        # Tighter bounce thresholds for better entry precision
        bounce_threshold: [0.002, 0.003, 0.004, 0.005]
        
        # Smaller profit targets for higher win rate
        exit_threshold: [0.001, 0.0015, 0.002, 0.0025]

# This generates 5 * 3 * 4 * 4 = 240 combinations