# Swing Pivot Bounce with Target-Based Exit - 5 Minute Timeframe
# Test on 5m data - balance between noise reduction and trade frequency
name: swing_pivot_bounce_target_5m
mode: signal_generation
symbols: ["SPY_5m"]  # 5m data
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Use parameters adapted for 5m
strategy:
  swing_pivot_bounce_target:
    params:
      sr_period: 24           # 2 hours on 5m (similar to 30 bars on 15m)
      min_touches: 4          
      bounce_threshold: 0.004 # Keep best value from 15m
      target_threshold: 0.004 # Keep best value from 15m

# Optimization for 5m timeframe
parameter_space:
  strategies:
    - type: swing_pivot_bounce_target
      param_overrides:
        # SR periods for 5m (1-4 hours of lookback)
        sr_period: [12, 18, 24, 30, 36, 48]
        
        # Keep successful touch requirements
        min_touches: [3, 4, 5]
        
        # Test tighter and same bounce thresholds
        bounce_threshold: [0.0025, 0.003, 0.0035, 0.004, 0.0045]
        
        # Fine-tune around the optimal 0.004 target threshold
        target_threshold: [0.003, 0.0035, 0.004, 0.0045, 0.005]

# This generates 6 * 3 * 5 * 5 = 450 combinations