# Swing Pivot Bounce Strategy - Refined Optimization
# Focus on best-performing parameter ranges from previous analysis
name: swing_pivot_bounce_refined
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Base configuration using best values
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 35
      min_touches: 4
      bounce_threshold: 0.004
      exit_threshold: 0.0015

# Refined parameter space around best performers
parameter_space:
  strategies:
    - type: swing_pivot_bounce
      param_overrides:
        # Focus on longer periods that performed better
        sr_period: [30, 35, 40, 45, 50]
        
        # More touches performed better
        min_touches: [3, 4, 5]
        
        # Narrow range around best bounce threshold
        bounce_threshold: [0.0035, 0.004, 0.0045, 0.005]
        
        # Focus heavily on 0.0015 which was far superior
        # Test slightly above and below
        exit_threshold: [0.0012, 0.0014, 0.0015, 0.0016, 0.0018]

# This generates 5 * 3 * 4 * 5 = 300 combinations