# Swing Pivot Bounce with Target-Based Exit Strategy
# Exit near the opposite S/R level instead of at midpoint
name: swing_pivot_bounce_target_test
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Test the new target-based exit strategy
strategy:
  swing_pivot_bounce_target:
    params:
      sr_period: 35           # Best from previous analysis
      min_touches: 4          # Best from previous analysis
      bounce_threshold: 0.004 # Best from previous analysis
      target_threshold: 0.003 # Exit 0.3% before hitting opposite level

# Optimization to find best target threshold
parameter_space:
  strategies:
    - type: swing_pivot_bounce_target
      param_overrides:
        # Use best parameters from previous analysis
        sr_period: [30, 35, 40]
        min_touches: [3, 4, 5]
        bounce_threshold: [0.003, 0.004, 0.005]
        
        # Test different exit distances from target (as % of price)
        # Smaller = exit closer to target (more profit but riskier)
        # Larger = exit farther from target (less profit but safer)
        # E.g., 0.002 = exit when 0.2% away from resistance/support
        target_threshold: [0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.004, 0.005]

# This generates 3 * 3 * 3 * 8 = 216 combinations