# Swing Pivot Bounce Strategy - 15 Minute Timeframe (Optimized)
# Parameters optimized for 15-minute timeframe and lower execution costs
name: swing_pivot_bounce_15m_optimized
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features - optimized for 15m timeframe
feature_config:
  support_resistance_16:  # Shorter lookback for more responsive levels
    type: support_resistance
    lookback: 16         # 16 bars = 4 hours on 15m
    min_touches: 2       # Keep standard touches requirement

# Strategy configuration - optimized for 15m
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 16           # Faster S/R detection (4 hours)
      min_touches: 2          # Standard validation
      bounce_threshold: 0.0025 # 0.25% - wider for 15m volatility
      exit_threshold: 0.0012   # 0.12% - larger profit target on 15m