# Swing Pivot Bounce Strategy - Improved Win Rate Focus
# Keep reasonable trade frequency but improve win rate and risk/reward
name: swing_pivot_bounce_improved
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Focus on better entry precision and risk/reward
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 30          # Moderate lookback (7.5 hours)
      min_touches: 3         # Standard touch requirement
      bounce_threshold: 0.004 # 0.4% - tighter for better entries
      exit_threshold: 0.003   # 0.3% - smaller target for higher win rate