# Swing Pivot Bounce Zones - High Frequency Configuration
# Optimized to generate 3000+ trades for filtering
name: swing_pivot_bounce_zones_5m_high_freq
mode: signal_generation
symbols: ["SPY_5m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Base configuration for high frequency
strategy:
  swing_pivot_bounce_zones:
    params:
      sr_period: 20          # Standard lookback
      min_touches: 2         # Lower requirement for more signals
      entry_zone: 0.001      # Very tight - 0.1% zone
      exit_zone: 0.0005      # Very tight - 0.05% zone
      min_range: 0.001       # Very low - 0.1% minimum range

# Optimization for maximum trades
parameter_space:
  strategies:
    - type: swing_pivot_bounce_zones
      param_overrides:
        # Standard SR periods
        sr_period: [12, 20, 30]
        
        # Lower touch requirements for more levels
        min_touches: [2, 3]
        
        # Much tighter entry zones for more signals
        entry_zone: [0.0005, 0.00075, 0.001, 0.00125, 0.0015]
        
        # Much tighter exit zones
        exit_zone: [0.0003, 0.0005, 0.00075, 0.001, 0.00125]
        
        # Very low minimum range to catch all S/R
        min_range: [0.0005, 0.001, 0.0015, 0.002]

# This generates 3 * 2 * 5 * 5 * 4 = 600 combinations
# Should generate 1000-5000 trades per strategy for filtering