# Swing Pivot Bounce Strategy - Targeted Optimization
# Focus on parameter ranges that should reduce overtrading and improve win rate
name: swing_pivot_bounce_targeted_optimize
mode: signal_generation
symbols: ["SPY_15m"]
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Base conservative configuration
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 60
      min_touches: 5
      bounce_threshold: 0.01
      exit_threshold: 0.005

# Targeted parameter space - focus on quality over quantity
parameter_space:
  strategies:
    - type: swing_pivot_bounce
      param_overrides:
        # Long lookbacks only (4-10 hours on 15m)
        sr_period: [60, 80, 100, 120]
        
        # High touch requirements only
        min_touches: [4, 5, 6, 7]
        
        # Wide bounce thresholds to be selective
        bounce_threshold: [0.008, 0.01, 0.012, 0.015]
        
        # Balanced profit targets (risk/reward)
        exit_threshold: [0.004, 0.005, 0.006, 0.008]

# This generates 4 * 4 * 4 * 4 = 256 combinations focused on conservative parameters