# Test configuration for Swing Pivot Bounce strategy
name: test_swing_pivot_bounce
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  swing_pivot_bounce:
    params:
      sr_period: 20  # Lookback period for S/R detection
      min_touches: 2  # Minimum touches to confirm level
      bounce_threshold: 0.002  # 0.2% proximity for bounce detection

# Run with: python main.py --config config/indicators/structure/test_swing_pivot_bounce.yaml --signal-generation --bars 100

# Expected behavior (MEAN REVERSION):
# - Price near/touching support: BUY signal (1) - expect bounce up
# - Price near/touching resistance: SELL signal (-1) - expect bounce down
# - Price away from levels: No signal (0)

# Uses dynamic support/resistance levels based on swing highs/lows
# Pairs with swing_pivot_breakout but trades bounces instead of breaks