# Test configuration for Pivot Points strategy
name: test_pivot_points
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  pivot_points:
    params:
      pivot_type: standard  # standard, fibonacci, or woodie
      timeframe: 1m  # 1m, 5m, 15m, 30m, 1h, 4h, D

# Run with: python main.py --config config/indicators/structure/test_pivot_points.yaml --signal-generation --bars 100

# Expected behavior (BREAKOUT):
# - Price > R1 (first resistance): BUY signal (1) - bullish breakout
# - Price < S1 (first support): SELL signal (-1) - bearish breakdown
# - S1 <= Price <= R1: No signal (0) - ranging

# Pivot points are calculated from previous period's high/low/close
# Standard pivots: P = (H + L + C) / 3
# R1 = 2*P - L, S1 = 2*P - H