backtest:
  csv_path: data/SPY.csv
  data_source: csv
  end_date: '2024-01-05'
  initial_capital: 100000
  start_date: '2024-01-01'
execution:
  broker: backtest
  costs:
    commission: 1.0
    slippage_pct: 0.1
risk:
  position_sizer:
    params:
      amount: 1000
    type: fixed_dollar
  risk_limits:
    max_exposure_pct: 90
    max_position_pct: 20
    max_positions: 10
strategies:
- name: simple_momentum
  params:
    fast_period: 5
    slow_period: 10
    threshold: 0.01
  type: momentum
