# ADMF-PC Signal Generation Demo Configuration
# This demonstrates the complete signal flow using main.py --signal-generation

# Data configuration
symbols: ['SPY']
timeframes: ['1D']
max_bars: 50  # Enough data for both SMAs

# Data source settings
data_source: file
data_path: 'data/SPY_1d.csv'
data_dir: './data'

# Strategy configuration
strategies:
  - name: 'ma_crossover_demo'
    type: 'ma_crossover'
    params:
      fast_period: 5
      slow_period: 20

# Portfolio configuration
initial_capital: 100000

# Execution settings
execution:
  max_duration: 10.0  # seconds to wait for completion
  enable_event_tracing: true
  trace_settings:
    storage_backend: 'hierarchical'
    enable_console_output: true
    console_filter: ['SIGNAL']
    container_settings:
      'portfolio*':
        enabled: true
        max_events: 1000
    batch_size: 100
    trace_dir: './workspaces'

# Results configuration
results:
  enable_analysis: true
  save_signals: true
  save_metrics: true

# Metadata
metadata:
  workflow_id: 'signal_generation_demo'
  description: 'Complete signal generation flow demonstration'
  created_at: '2025-06-11'