# Minimal test config for sparse storage
symbols: ['SPY']
timeframes: ['1D']
max_bars: 50

strategies:
  - name: 'ma_crossover_demo'
    type: 'ma_crossover'
    params:
      fast_period: 5
      slow_period: 20

initial_capital: 100000

execution:
  enable_event_tracing: true
  trace_settings:
    use_sparse_storage: true
    enable_console_output: false
    container_settings:
      'portfolio*':
        enabled: true

metadata:
  workflow_id: 'sparse_test'