name: bollinger
data: SPY_5m

strategy: [
  {
    bollinger_bands: {
      period: 20, 
      std_dev: 2.5,
      threshold: "volume > volume_sma_20 * 1.3 or volatility_percentile_50 > 0.4 or abs(linreg_20_slope) < 0.15 or (rsi_14 < 35 or rsi_14 > 65)"
    }
  }
]

# best single performer:   {bollinger_bands: {period: 11, std_dev: 2.0}}
# performs ideally with 0.1% stop
# performed good IN/OOS
# filtered version above may outperform 