# Test configuration for Stochastic Divergence strategy
name: test_stochastic_divergence
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Stochastic divergence reversal strategy
strategy:
  stochastic_divergence:
    params:
      k_period: 14
      d_period: 3
      swing_lookback: 5
      oversold_level: 20
      overbought_level: 80

# Run with: python main.py --config config/indicators/divergence/test_stochastic_divergence.yaml --signal-generation --bars 100

# Expected behavior (REVERSAL):
# - At swing low in oversold zone: If stoch shows strength -> BUY (1)
# - At swing high in overbought zone: If stoch shows weakness -> SELL (-1)
# - Otherwise: No signal (0)

# Most reliable divergences occur:
# - In extreme zones (< 20 or > 80)
# - With clear swing points
# - When %K shows clear divergence from price