# Bollinger Band + RSI Zones Strategy
# Clear zone-based approach with explicit flat signals
name: bollinger_rsi_zones
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features - simple and minimal
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14

# Strategy configuration
strategy:
  bollinger_rsi_zones:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_divergence_long: 30    # RSI > 30 when price below lower band
      rsi_divergence_short: 70   # RSI < 70 when price above upper band
      exit_at_middle: true       # Generate flat signals near middle band