# Bollinger Band + RSI Divergence Strategy - Fixed Exit Logic
# This version properly exits at middle band and has configurable hold times
name: bollinger_rsi_dependent_fixed
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  bb_rsi_dependent:
    - lookback: 20
      rsi_divergence_threshold: 2.0  # Lowered from 5.0 for more signals
      confirmation_bars: 10
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14

# Strategy configuration
strategy:
  bollinger_rsi_dependent_fixed:
    params:
      exit_at_middle_band: true
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback: 20
      rsi_divergence_threshold: 2.0  # Must match feature config
      confirmation_bars: 10
      max_hold_bars: 200  # Force exit after ~3.3 hours
      quick_exit_bars: 30  # Quick exit at middle band within 30 bars