# Bollinger Band + RSI Simple Signals - 5 Minute Timeframe (Tuned)
# Parameters adjusted for 5-minute characteristics
name: bollinger_rsi_simple_signals_5m_tuned
mode: signal_generation
symbols: ["SPY_5m"]  # Use the 5-minute data file
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features - tuned for 5m
feature_config:
  bollinger_bands:
    - period: 18    # 90 minutes (faster than standard 20)
      std_dev: 2.1  # Slightly wider for 5m volatility
  rsi:
    - period: 12    # Faster RSI for 5m
  # Additional confirmation features
  sma:
    - period: 60    # 5-hour trend (60 * 5min)

# Strategy configuration tuned for 5m
strategy:
  bollinger_rsi_simple_signals:
    params:
      bb_period: 18
      bb_std: 2.1
      rsi_period: 12
      rsi_threshold: 11  # Slightly higher threshold for 5m
      
# Risk parameters for 5m timeframe
risk:
  position_size: 0.02  # 2% per position
  max_positions: 4     # Allow more positions than 15m
  stop_loss_pct: 0.3   # 0.3% stop loss (tighter than 15m)
  take_profit_pct: 0.6 # 0.6% take profit target