# Bollinger Band + RSI Divergence Strategy - Quick Exit Version
# This version exits more quickly using multiple exit conditions
name: bollinger_rsi_quick_exit
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  bb_rsi_dependent:
    - lookback: 20
      rsi_divergence_threshold: 2.0  # Lowered for more signals
      confirmation_bars: 10
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14

# Strategy configuration
strategy:
  bollinger_rsi_quick_exit:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback: 20
      rsi_divergence_threshold: 2.0  # Must match feature config
      confirmation_bars: 10
      profit_target_pct: 0.003  # Exit at 0.3% profit
      stop_loss_pct: 0.005      # Exit at 0.5% loss
      middle_band_exit_after: 20  # Can exit at middle band after 20 bars