# Bollinger Bands with RSI divergence filtering
# Uses the standard BB strategy but filters for divergence patterns
name: bollinger_with_rsi_filter
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

# Required features for filtering
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14

# Standard Bollinger strategy with RSI filters
strategy:
  bollinger_bands:
    params:
      period: 20
      std_dev: 2.0
      exit_threshold: 0.001  # Exit at middle band
    
    # Filter for RSI divergence patterns
    filter:
      # Long entry: Price at lower band but RSI NOT oversold (bullish divergence)
      - condition: "signal_value > 0 and rsi_14 > 35"
        action: "allow"
        
      # Short entry: Price at upper band but RSI NOT overbought (bearish divergence)  
      - condition: "signal_value < 0 and rsi_14 < 65"
        action: "allow"
        
      # Reject all other entry signals
      - condition: "signal_value != 0"
        action: "reject"

# This implements the divergence pattern:
# - Price at extreme (Bollinger handles this)
# - RSI not at extreme (filter handles this)
# - Exit at middle band (Bollinger handles this)

# Run with:
# python main.py --config config/indicators/volatility/bollinger_with_rsi_filter.yaml --signal-generation --bars 10000