# Bollinger Band + True RSI Divergence Strategy
# Uses actual RSI divergences (comparing highs/lows over time)
name: bollinger_rsi_true_divergence
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  rsi_divergence:
    - rsi_period: 14
      lookback_bars: 30        # Look back up to 30 bars for extremes
      min_bars_between: 3      # Extremes must be at least 3 bars apart
      rsi_divergence_threshold: 3.0   # RSI must differ by at least 3 points
      price_threshold_pct: 0.0005     # Price must differ by at least 0.05%

# Strategy configuration
strategy:
  bollinger_rsi_true_divergence:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback_bars: 30
      min_bars_between: 3
      rsi_divergence_threshold: 3.0
      price_threshold_pct: 0.0005
      require_band_extreme: true    # Require BB extreme for entry
      exit_at_middle: true         # Exit when price returns to middle band