# Bollinger Band + RSI Simple Signals - 5 Minute Timeframe
# Middle ground between 1m (too many trades) and 15m (fewer trades)
name: bollinger_rsi_simple_signals_5m
mode: signal_generation
symbols: ["SPY_5m"]  # Use the 5-minute data file
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20    # 20 periods = 100 minutes on 5m timeframe
      std_dev: 2.0
  rsi:
    - period: 14    # Standard RSI period

# Strategy configuration
strategy:
  bollinger_rsi_simple_signals:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_threshold: 10  # RSI must be 10+ points away from extreme (30/70)