# Simplified Bollinger + RSI strategy (approximates divergence)
name: bollinger_rsi_simple
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14

# Strategy configuration
strategy:
  bollinger_rsi_simple:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_os_level: 30    # RSI oversold level
      rsi_ob_level: 70    # RSI overbought level
      exit_threshold: 0.001  # Exit within 0.1% of middle band

# This strategy approximates divergence by:
# - Long when price hits lower band but RSI > 30 (not oversold)
# - Short when price hits upper band but RSI < 70 (not overbought)
# - Exit at middle band

# Run with:
# python main.py --config config/indicators/volatility/bollinger_rsi_simple.yaml --signal-generation --bars 5000