# Bollinger Band + RSI Divergence with Proper Exits
# Uses the stateful divergence feature but adds exit-to-flat logic
name: bollinger_rsi_with_exits
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  bb_rsi_dependent:
    - lookback: 20
      rsi_divergence_threshold: 2.0  # Lowered for more signals
      confirmation_bars: 10
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14

# Strategy configuration
strategy:
  bollinger_rsi_with_exits:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback: 20
      rsi_divergence_threshold: 2.0  # Must match feature config
      confirmation_bars: 10
      min_bars_before_new_signal: 20  # Wait before new entry
      exit_on_middle_band: true        # Exit when price returns to middle
      exit_on_rsi_neutral: true        # Exit when RSI is 45-55