# Bollinger Bands filtered by volatility regime
name: bollinger_volatility_filter
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

feature_config:
  atr:
    - period: 14
  sma:
    - period: 50  # For ATR comparison

strategy:
  bollinger_bands:
    params:
      period: 20
      std_dev: 2.0
      entry_buffer: 0.005
      exit_mode: 'middle'
    
    # Volatility-based filtering
    filter:
      # Only trade when ATR is above its 50-period average (higher volatility)
      - condition: "signal_value != 0 and atr_14 > sma_50_of_atr"
        action: "allow"
      - condition: "signal_value != 0"
        action: "reject"
        
    # Note: You'd need to add sma_50_of_atr as a custom feature
    # Or use a simpler filter like: atr_14 > 0.01 (1% of price)