# Bollinger Band + RSI Simple Signals - 15 Minute Timeframe
# Generates signals based on current conditions only - no position tracking
# Adjusted for 15-minute bars to capture larger moves
name: bollinger_rsi_simple_signals_15m
mode: signal_generation
symbols: ["SPY_15m"]  # Use the 15-minute data file
start_date: "2024-04-01"
end_date: "2024-12-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20    # 20 periods = 5 hours on 15m timeframe
      std_dev: 2.0
  rsi:
    - period: 14    # Standard RSI period works well across timeframes

# Strategy configuration
strategy:
  bollinger_rsi_simple_signals:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_threshold: 10  # RSI must be 10+ points away from extreme (30/70)
      
# Optional: Add execution parameters for 15m timeframe
# execution:
#   slippage_pct: 0.05    # Lower slippage expected on 15m vs 1m
#   commission: 0.0005    # Commission per trade
#   min_move_pct: 0.15    # Minimum expected move on 15m (larger than 1m)