# Exact Bollinger + RSI Divergence implementation from profitable backtest
# This uses a clever workaround to track multi-bar patterns
name: bollinger_rsi_exact
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14

# Use the tracker strategy with exact parameters
strategy:
  bollinger_rsi_tracker:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_divergence_threshold: 5.0
      lookback_bars: 20
      confirmation_bars: 10
      exit_threshold: 0.001  # Exit at middle band

# This implements the exact pattern:
# 1. Track when price goes outside bands
# 2. Look for divergence (price new extreme, RSI doesn't confirm)
# 3. Enter when price comes back inside (confirmation)
# 4. Exit at middle band

# Expected results (from backtest):
# - ~494 trades (38/month)
# - 71.9% win rate
# - 11.82% net return
# - Average 12 bar holding period

# Run with:
# python main.py --config config/indicators/volatility/bollinger_rsi_exact.yaml --signal-generation --bars 10000