# Final Bollinger + RSI Divergence implementation
# Uses the proper self-contained feature that tracks multi-bar patterns
name: bollinger_rsi_final
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

# Feature configuration - the divergence tracker computes BB and RSI internally
feature_config:
  bb_rsi_divergence_proper:
    - bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback: 20
      rsi_divergence_threshold: 5.0
      confirmation_bars: 10

# Simple strategy that uses the divergence signals
strategy:
  bollinger_rsi_final:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_divergence_threshold: 5.0
      lookback_bars: 20
      confirmation_bars: 10
      exit_threshold: 0.001  # Exit at middle band

# This implements the EXACT pattern from the profitable backtest:
# 1. Tracks when price goes outside Bollinger Bands
# 2. Records RSI value at those extremes
# 3. Detects divergence: price makes new extreme, RSI doesn't
# 4. Confirms when price returns inside bands
# 5. Exits at middle band

# Expected results (matching backtest):
# - ~494 trades
# - 71.9% win rate
# - 11.82% net return
# - Average 12 bar holding period

# Run with:
# python main.py --config config/indicators/volatility/bollinger_rsi_final.yaml --signal-generation --bars 10000