# Bollinger Bands with stricter RSI divergence filtering
# Attempts to better approximate the multi-bar divergence pattern
name: bollinger_rsi_strict_filter
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

# Required features for filtering
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  # Add SMA for additional filtering
  sma:
    - period: 20  # Same as BB middle

# Standard Bollinger strategy with much stricter filters
strategy:
  bollinger_bands:
    params:
      period: 20
      std_dev: 2.0
      exit_threshold: 0.005  # Looser exit - 0.5% from middle (was 0.1%)
    
    # Much stricter filters to reduce false signals
    filter:
      # Long entry: Strong divergence pattern
      # Price at lower band but RSI showing real strength
      - condition: "signal_value > 0 and rsi_14 > 40 and rsi_14 < 50"
        action: "allow"
        
      # Short entry: Strong divergence pattern
      # Price at upper band but RSI showing real weakness
      - condition: "signal_value < 0 and rsi_14 < 60 and rsi_14 > 50"
        action: "allow"
        
      # Additional filter: Only trade when price has moved significantly
      # This helps ensure we're catching rebounds, not just touches
      - condition: "signal_value != 0 and band_position > 0.1 and band_position < 0.9"
        action: "allow"
        
      # Reject all other signals
      - condition: "signal_value != 0"
        action: "reject"

# Key changes:
# 1. Much tighter RSI ranges (40-50 for longs, 50-60 for shorts)
# 2. Looser exit threshold (0.5% vs 0.1%) to allow trades to develop
# 3. Band position filter to avoid immediate entries

# Run with:
# python main.py --config config/indicators/volatility/bollinger_rsi_strict_filter.yaml --signal-generation --bars 10000