# Bollinger Band + RSI with Volatility Filter
# Filters out medium volatility periods based on analysis
name: bollinger_rsi_volatility_filtered
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  atr:
    - period: 14

# Strategy configuration
strategy:
  bollinger_rsi_volatility_filtered:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_threshold: 10  # RSI must be 10+ points away from extreme
      atr_period: 14
      volatility_filter: "exclude_medium"  # Options: none, exclude_medium, high_only
      low_vol_threshold: 0.5   # ATR < 0.5% = low volatility
      high_vol_threshold: 1.0  # ATR > 1.0% = high volatility