# Test configuration for Keltner Bands (mean reversion)
name: test_keltner_bands
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  keltner_bands:
    params:
      period: 20
      multiplier: 2.0

# Run with: python main.py --config config/indicators/volatility/test_keltner_bands.yaml --signal-generation --bars 100

# Expected behavior (MEAN REVERSION):
# - Price >= Upper Band: SELL signal (-1) - overbought
# - Price <= Lower Band: BUY signal (1) - oversold
# - Price within bands: No signal (0)

# Keltner channels use EMA + ATR for adaptive bands