# Test configuration for Keltner Channel Breakout strategy
name: test_keltner_breakout
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  keltner_breakout:
    params:
      period: 20
      multiplier: 2.0

# Run with: python main.py --config config/indicators/volatility/test_keltner_breakout.yaml --signal-generation --bars 100

# Expected behavior (TREND FOLLOWING):
# - Price > Upper Channel: BUY signal (1) - bullish breakout
# - Price < Lower Channel: SELL signal (-1) - bearish breakout
# - Price within channel: No signal (0)

# Keltner channels use ATR for dynamic width
# More adaptive to volatility than Bollinger bands