# Test configuration for Bollinger Breakout strategy
name: test_bollinger_breakout
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  bollinger_breakout:
    params:
      period: 20
      std_dev: 2.0

# Run with: python main.py --config config/indicators/volatility/test_bollinger_breakout.yaml --signal-generation --bars 100

# Expected behavior (TREND FOLLOWING):
# - Price > Upper Band: BUY signal (1) - bullish breakout
# - Price < Lower Band: SELL signal (-1) - bearish breakout
# - Price within bands: No signal (0)

# This is a trend-following breakout strategy
# Opposite of bollinger_bands which is mean reversion