# Minimal Keltner Bands configuration
name: test_keltner_minimal
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-10-01"
end_date: "2024-10-31"

# Just the strategy, no parameter space
strategy:
  keltner_bands:
    params:
      period: 20
      multiplier: 2.0