# Test configuration for Accumulation/Distribution strategy
name: test_accumulation_distribution
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Accumulation/Distribution Line crossover strategy
strategy:
  accumulation_distribution:
    params:
      ema_period: 20

# Run with: python main.py --config config/indicators/volume/test_accumulation_distribution.yaml --signal-generation --bars 100

# Expected behavior:
# - A/D Line > EMA(20): BUY signal (1) - accumulation phase
# - A/D Line < EMA(20): SELL signal (-1) - distribution phase
# - A/D Line = EMA(20): No signal (0)

# A/D Line tracks money flow into/out of a security
# Rising A/D = accumulation (smart money buying)
# Falling A/D = distribution (smart money selling)
# Divergences with price can signal reversals