# Test configuration for Chaikin Money Flow strategy
name: test_chaikin_money_flow
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Chaikin Money Flow strategy
strategy:
  chaikin_money_flow:
    params:
      period: 20
      threshold: 0.05  # 5% threshold

# Run with: python main.py --config config/indicators/volume/test_chaikin_money_flow.yaml --signal-generation --bars 100

# Expected behavior:
# - CMF > 0.05: BUY signal (1) - buying pressure
# - CMF < -0.05: SELL signal (-1) - selling pressure
# - CMF between -0.05 and 0.05: No signal (0)

# CMF measures accumulation/distribution over time
# Positive CMF = buying pressure (close near high)
# Negative CMF = selling pressure (close near low)
# Values range from -1 to +1