# Test configuration for RSI Threshold strategy
name: test_rsi_threshold
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  rsi_threshold:
    params:
      rsi_period: 14
      threshold: 50

# Run with: python main.py --config config/indicators/test_rsi_threshold.yaml --signal-generation --bars 100

# Expected behavior:
# - RSI > 50: BUY signal (1) - momentum above neutral
# - RSI < 50: SELL signal (-1) - momentum below neutral
# - RSI = 50: No signal (0)

# This is a momentum strategy using RSI as directional indicator
# Different from rsi_bands which is mean reversion at extremes