# Test configuration for Williams %R strategy
name: test_williams_r
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy with fixed parameters
strategy:
  williams_r:
    params:
      williams_period: 14
      oversold: -80
      overbought: -20

# Run with: python main.py --config config/indicators/oscillator/test_williams_r.yaml --signal-generation --bars 100

# Expected behavior:
# - Williams %R < -80: BUY signal (1) - oversold
# - Williams %R > -20: SELL signal (-1) - overbought
# - -80 <= Williams %R <= -20: No signal (0)

# Note: Williams %R ranges from -100 to 0
# More negative = more oversold