# Test configuration for Ultimate Oscillator strategy
name: test_ultimate_oscillator
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Ultimate Oscillator mean reversion strategy
strategy:
  ultimate_oscillator:
    params:
      period1: 7    # Fast period
      period2: 14   # Medium period
      period3: 28   # Slow period
      overbought: 70
      oversold: 30

# Run with: python main.py --config config/indicators/oscillator/test_ultimate_oscillator.yaml --signal-generation --bars 100

# Expected behavior (MEAN REVERSION):
# - UO > 70: SELL signal (-1) - overbought
# - UO < 30: BUY signal (1) - oversold
# - UO between 30-70: No signal (0)

# Ultimate Oscillator combines three timeframes to reduce false signals
# More reliable than single-period oscillators
# Values range from 0 to 100