# Backtest Pattern
# Complete backtest pipeline: data → features → strategies → portfolios → risk → execution

name: backtest
description: Full backtest with data → features → strategies → portfolios → risk → execution

# Stateless components to create
components:
  - type: strategies
    from_config: strategies  # Get from user config

  - type: risk_validators
    from_config: risk_profiles

  - type: classifiers
    from_config: classifiers
    default: []

  - type: execution_models
    from_config: execution_models
    default: []

# Containers to create
containers:
  # Data containers - one per symbol/timeframe combo
  - name_template: "{symbol}_{timeframe}_data"
    type: data
    foreach:
      symbol:
        from_config: symbols
      timeframe:
        from_config: timeframes
    config:
      symbol: "{symbol}"
      timeframe: "{timeframe}"
      data_source:
        from_config: data_source
        default: file
      data_path:
        from_config: data_path
      start_date:
        from_config: start_date
      end_date:
        from_config: end_date

  # Feature containers - one per data container
  - name_template: "{symbol}_{timeframe}_features"
    type: features
    foreach:
      symbol:
        from_config: symbols
      timeframe:
        from_config: timeframes
    config:
      symbol: "{symbol}"
      timeframe: "{timeframe}"
      data_container: "{symbol}_{timeframe}_data"  # Reference to data container
      features:
        from_config: features
        default: {}

  # Portfolio containers - one per strategy/risk combo
  - name_template: "portfolio_{combo_id}"
    type: portfolio
    foreach:
      combo: "$generated.parameter_combinations"
    config:
      combo_id: "{combo_id}"
      strategy_type: "{combo.strategy_params.type}"
      strategy_params: "{combo.strategy_params}"
      risk_type: "{combo.risk_params.type}"
      risk_params: "{combo.risk_params}"
      initial_capital:
        from_config: initial_capital
        default: 100000
      objective_function:
        from_config: objective_function
        default:
          name: sharpe_ratio
      results:
        from_config: results
        default: {}
      metrics:
        from_config: metrics
        default: {}

  # Single execution container
  - name: execution
    type: execution
    config:
      mode: backtest
      execution_models:
        from_config: execution_models
        default: []

# Routes to create
routes:
  # Risk validation route - validates orders from portfolios
  - name: risk_validation
    type: risk_service
    source_pattern: "portfolio_*"
    target: "$root_event_bus"

  # Fill broadcast - sends fills from execution to portfolios
  - name: fill_broadcast
    type: broadcast
    source: execution
    targets: "portfolio_*"
    allowed_types: [FILL]

# Special behaviors
behaviors:
  # Feature dispatcher - routes features to appropriate strategies
  - type: feature_dispatcher
    source_pattern: "*_features"
    target: strategies

  # Subscribe portfolios to signals
  - type: subscribe_to_root_bus
    containers: "portfolio_*"
    event_type: SIGNAL
    handler: signal_processor.on_signal

  # Subscribe execution to orders
  - type: subscribe_to_root_bus
    containers: execution
    event_type: ORDER
    handler: execution_engine.on_order