# Signal Generation Pattern
# Pipeline for generating and saving signals: data → strategies (signals saved)

name: signal_generation
description: Generate trading signals and save to disk for later replay

# Stateless components
components:
  - type: strategies
    from_config: strategies

  - type: classifiers
    from_config: classifiers
    default: []

# Root container with child containers
containers:
  - name: root
    type: root
    config:
      components: []  # No components at root level
      
    # Child containers defined inline
    containers:
      # Data containers - one per symbol/timeframe combo
      - name_template: "{symbol}_{timeframe}_data"
        type: data
        components: ["data_streamer"]
        foreach:
          symbol:
            from_config: symbols
          timeframe:
            from_config: timeframes
        config:
          symbol: "{symbol}"
          timeframe: "{timeframe}"
          data_source:
            from_config: data_source
            default: file
          data_path:
            from_config: data_path
          data_dir:
            from_config: data_dir
            default: ./data
          start_date:
            from_config: start_date
          end_date:
            from_config: end_date
          max_bars:
            from_config: max_bars

      # Strategy containers - one per symbol/timeframe
      - name_template: "{symbol}_{timeframe}_strategy"
        type: strategy
        components: ["strategy_state"]
        foreach:
          symbol:
            from_config: symbols
          timeframe:
            from_config: timeframes
        config:
          symbols: ["{symbol}"]
          features:
            from_config: feature_configs
            default: {}
          strategies:
            from_config: strategies
            default: []
      
      # Portfolio containers - one per strategy to collect its signals
      # These act as filters, capturing only signals from specific strategies
      - name_template: "portfolio_{strategy_name}"
        type: portfolio
        components: ["portfolio_manager", "position_manager"]
        foreach:
          strategy_name:
            from_config: strategy_names
            default: ["default"]
        config:
          managed_strategies: ["{strategy_name}"]
          signal_collection_only: true  # Don't execute trades, just collect signals

# Routes to create
routes:
  # Signal saver - captures and saves all signals
  - name: signal_saver
    type: signal_saver
    source: "$root_event_bus"
    save_directory:
      from_config: signal_save_directory
      default: "./results/signals/"

# Special behaviors
behaviors:
  # Feature dispatcher - routes features to strategies
  - type: feature_dispatcher
    source_pattern: "*_features"
    target: strategies