# Signal Generation Pattern
# Pipeline for generating and saving signals: data → features → strategies (signals saved)

name: signal_generation
description: Generate trading signals and save to disk for later replay

# Stateless components
components:
  - type: strategies
    from_config: strategies

  - type: classifiers
    from_config: classifiers
    default: []

# Containers to create
containers:
  # Data containers - one per symbol/timeframe combo
  - name_template: "{symbol}_{timeframe}_data"
    type: data
    foreach:
      symbol:
        from_config: symbols
      timeframe:
        from_config: timeframes
    config:
      symbol: "{symbol}"
      timeframe: "{timeframe}"
      data_source:
        from_config: data_source
        default: file
      data_path:
        from_config: data_path
      start_date:
        from_config: start_date
      end_date:
        from_config: end_date

  # Feature containers - one per data container
  - name_template: "{symbol}_{timeframe}_features"
    type: features
    foreach:
      symbol:
        from_config: symbols
      timeframe:
        from_config: timeframes
    config:
      symbol: "{symbol}"
      timeframe: "{timeframe}"
      data_container: "{symbol}_{timeframe}_data"
      features:
        from_config: features
        default: {}

# Routes to create
routes:
  # Signal saver - captures and saves all signals
  - name: signal_saver
    type: signal_saver
    source: "$root_event_bus"
    save_directory:
      from_config: signal_save_directory
      default: "./results/signals/"

# Special behaviors
behaviors:
  # Feature dispatcher - routes features to strategies
  - type: feature_dispatcher
    source_pattern: "*_features"
    target: strategies