# Signal Generation Pattern with Strategy-Level Tracing
# Pipeline for generating and saving signals at the strategy source

name: signal_generation_strategy_trace
description: Generate trading signals with strategy-level sparse tracing

# Stateless components
components:
  - type: strategies
    from_config: strategies

  - type: classifiers
    from_config: classifiers
    default: []

# Root container with child containers
containers:
  - name: root
    type: root
    config:
      components: []  # No components at root level
      
    # Child containers defined inline
    containers:
      # Data containers - one per symbol/timeframe combo
      - name_template: "{symbol}_{timeframe}_data"
        type: data
        components: ["data_streamer"]
        foreach:
          symbol:
            from_config: symbols
          timeframe:
            from_config: timeframes
        config:
          symbol: "{symbol}"
          timeframe: "{timeframe}"
          data_source:
            from_config: data_source
            default: file
          data_path:
            from_config: data_path
          data_dir:
            from_config: data_dir
            default: ./data
          start_date:
            from_config: start_date
          end_date:
            from_config: end_date
          max_bars:
            from_config: max_bars

      # Strategy containers - one per symbol/timeframe
      # These will have strategy-level signal tracing enabled
      - name_template: "{symbol}_{timeframe}_strategy"
        type: strategy
        components: ["strategy_state"]
        foreach:
          symbol:
            from_config: symbols
          timeframe:
            from_config: timeframes
        config:
          symbols: ["{symbol}"]
          features:
            from_config: features
            default: {}
          strategies:
            from_config: strategies
            default: []
          # Pass through execution config to enable strategy tracing
          execution:
            from_config: execution
          metadata:
            from_config: metadata

# Routes to create
routes:
  # No routes needed - strategy containers trace their own signals

# Special behaviors
behaviors:
  # Feature dispatcher - routes features to strategies
  - type: feature_dispatcher
    source_pattern: "*_features"
    target: strategies