# DuckDB Ensemble Debug Configuration
# Uses shorter periods for more frequent regime changes and easier debugging

name: duckdb_ensemble_debug
description: Debug configuration for ensemble strategy with shorter periods

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data
start_date: "2024-03-26"
end_date: "2025-01-17"

# Topology 
topology: signal_generation

# Classifier configuration - shorter periods for more regime changes
classifiers:
  - type: volatility_momentum_classifier
    name: vol_mom_classifier
    params:
      vol_threshold: 0.8          # Lower threshold
      rsi_overbought: 60          # Less extreme
      rsi_oversold: 40
      atr_period: 14              # Much shorter - was 60
      rsi_period: 14              # Much shorter - was 30
      sma_period: 20              # Much shorter - was 60

# Simple ensemble strategy for debugging
strategies:
  - type: duckdb_ensemble
    name: debug_ensemble
    params:
      classifier_name: volatility_momentum_classifier
      aggregation_method: equal_weight
      min_agreement: 0.3
      # Pass classifier params to ensemble
      vol_threshold: 0.8
      rsi_overbought: 60
      rsi_oversold: 40
      atr_period: 14
      rsi_period: 14
      sma_period: 20
      # Simple regime strategies for testing
      regime_strategies:
        low_vol_bullish:
          - name: sma_crossover
            params:
              fast_period: 10
              slow_period: 20
        low_vol_bearish:
          - name: rsi_bands
            params:
              rsi_period: 14
              oversold: 30
              overbought: 70
        neutral:
          - name: cci_threshold
            params:
              cci_period: 14
              threshold: 0
        high_vol_bullish:
          - name: bollinger_breakout
            params:
              period: 20
              std_dev: 2.0
        high_vol_bearish:
          - name: keltner_breakout
            params:
              period: 20
              multiplier: 2.0

# Execution settings with debug logging
execution:
  enable_event_tracing: true
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    storage_backend: memory  # Use memory for faster debugging
    use_sparse_storage: true
    
# Metadata
metadata:
  experiment_id: duckdb_ensemble_debug
  description: |
    Debug configuration with:
    - Shorter indicator periods for more frequent regime changes
    - Simple strategies for each regime
    - Memory storage for faster iteration
    - Enhanced logging for debugging