name: keltner_regime_enhanced
symbols: ["SPY_5m"]

# Enhanced version of original config with regime filters
# Key fixes:
# 1. Changed "signal == 0 or" to "signal != 0 and" for proper filtering
# 2. Added regime-based filters from analysis
# 3. Focused on parameters that actually work

parameter_space:
  strategies:
    # 1. BASELINE - Proven parameters
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
    
    # 2. VOLATILITY FILTER
    # Only enter when volatility is elevated
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and 
        atr(14) > atr_sma(50) * ${atr_threshold}
      filter_params:
        atr_threshold: [1.0, 1.1, 1.2, 1.3]
    
    # 3. VWAP DIRECTIONAL FILTER
    # Long below VWAP, short above VWAP
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and (
          (signal > 0 and close < vwap) or
          (signal < 0 and close > vwap)
        )
    
    # 4. VWAP DISTANCE FILTER
    # Must be away from VWAP (not near it)
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and
        abs(close - vwap) / vwap > ${vwap_distance}
      filter_params:
        vwap_distance: [0.001, 0.002, 0.003]  # 0.1-0.3% away
    
    # 5. TIME OF DAY FILTER
    # Avoid midday (bars 30-48 = 12:00-2:30 PM)
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and
        (bar_of_day < 30 or bar_of_day > 48)
    
    # 6. COMBINED VOLATILITY + VWAP
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and
        atr(14) > atr_sma(50) * ${atr_threshold} and
        (
          (signal > 0 and close < vwap * ${long_vwap}) or
          (signal < 0 and close > vwap * ${short_vwap})
        )
      filter_params:
        atr_threshold: [1.1, 1.2]
        long_vwap: [0.999, 0.998]  # Below VWAP for longs
        short_vwap: [1.001, 1.002]  # Above VWAP for shorts
    
    # 7. RSI EXTREME FILTER (from original, but fixed)
    # Enter longs on oversold, shorts on overbought
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and (
          (signal > 0 and rsi(14) < ${rsi_oversold}) or
          (signal < 0 and rsi(14) > ${rsi_overbought})
        )
      filter_params:
        rsi_oversold: [30, 35, 40]
        rsi_overbought: [60, 65, 70]
    
    # 8. VOLUME SPIKE FILTER
    # Trade on above-average volume
    - type: keltner_bands
      param_overrides:
        period: [20]
        multiplier: [2.0]
      filter: |
        signal != 0 and
        volume > volume_sma(20) * ${volume_spike}
      filter_params:
        volume_spike: [1.2, 1.5, 2.0]
    
    # 9. MASTER REGIME FILTER
    # Combines all successful filters
    - type: keltner_bands
      param_overrides:
        period: [18, 20, 22]  # Test around optimal
        multiplier: [1.8, 2.0, 2.2]
      filter: |
        signal != 0 and
        atr(14) > atr_sma(50) * 1.1 and
        (bar_of_day < 30 or bar_of_day > 48) and
        abs(close - vwap) / vwap > 0.001 and
        (
          (signal > 0 and close < vwap and rsi(14) < 50) or
          (signal < 0 and close > vwap and rsi(14) > 50)
        )

# Key improvements from original:
# 1. Fixed filter logic (signal != 0 and X, not signal == 0 or X)
# 2. Added proven regime filters (volatility, VWAP, time)
# 3. Focused on period 20, multiplier 2.0 (proven optimal)
# 4. Removed combinations that showed poor performance
# Total: ~45 focused strategies vs 122 scattered