# Multi-Strategy Backtest Configuration
# Demonstrates the enhanced StrategyContainer with multiple strategies and signal aggregation

type: backtest
name: "Multi-Strategy Momentum Ensemble"

# Data configuration
data:
  source: "csv"
  file_path: "data/SPY_1m.csv"
  symbols: ["SPY"]
  start_date: null
  end_date: null
  frequency: "1m"
  max_bars: 100  # Limit for testing

# Multiple strategies configuration (handled by enhanced StrategyContainer)
strategies:
  - name: "fast_momentum"
    type: "momentum"
    weight: 0.4
    parameters:
      lookback_period: 5
      momentum_threshold: 0.002
      rsi_period: 14
      
  - name: "medium_momentum"
    type: "momentum"
    weight: 0.3
    parameters:
      lookback_period: 10
      momentum_threshold: 0.001
      rsi_period: 14
      
  - name: "slow_momentum"
    type: "momentum"
    weight: 0.3
    parameters:
      lookback_period: 20
      momentum_threshold: 0.0005
      rsi_period: 21

# Strategy container will be automatically configured as 'ensemble' type
# when multiple strategies are detected
strategy:
  # Signal aggregation configuration
  aggregation:
    method: "weighted_voting"
    min_confidence: 0.6
    consensus_threshold: 0.7

# Risk management
risk:
  initial_capital: 100000
  max_position_size_pct: 5.0
  max_portfolio_risk_pct: 15.0

# Portfolio allocation
portfolio:
  allocation_method: "equal_weight"
  initial_capital: 100000

# Execution settings
execution:
  mode: "backtest"
  commission: 0.001
  slippage: 0.0005

# Output settings
parameters:
  output_dir: "output/multi_strategy_test"