# Multi-Strategy Grid Search Configuration
# Uses existing infrastructure - just define multiple strategy instances

name: multi_strategy_grid_search
description: Grid search using multiple strategy configurations

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data
start_date: "2023-01-01"
end_date: "2023-02-01"
max_bars: 2000

# Topology pattern
topology_pattern: signal_generation

# Feature configuration - comprehensive set
feature_configs:
  sma_5:
    feature: sma
    period: 5
  sma_10:
    feature: sma
    period: 10
  sma_20:
    feature: sma
    period: 20
  sma_50:
    feature: sma
    period: 50
  rsi:
    feature: rsi
    period: 14
  rsi_fast:
    feature: rsi
    period: 7
  macd:
    feature: macd
    fast: 12
    slow: 26
    signal: 9
  momentum:
    feature: momentum
    periods: [5, 10, 20]
  atr:
    feature: atr
    period: 14
  volatility:
    feature: volatility
    period: 20

# Multiple strategy instances with different parameters
strategies:
  # Momentum strategies with different parameters
  - type: simple_momentum
    name: momentum_conservative
    params:
      sma_period: 20
      rsi_threshold_long: 30
      rsi_threshold_short: 70
      exit_bars: 10
      
  - type: simple_momentum
    name: momentum_aggressive
    params:
      sma_period: 10
      rsi_threshold_long: 25
      rsi_threshold_short: 75
      exit_bars: 5
      
  - type: simple_momentum
    name: momentum_balanced
    params:
      sma_period: 20
      rsi_threshold_long: 35
      rsi_threshold_short: 65
      exit_bars: 7
      
  # MA crossover variations
  - type: ma_crossover
    name: ma_fast_5_20
    params:
      fast_period: 5
      slow_period: 20
      stop_loss_pct: 1.0
      
  - type: ma_crossover
    name: ma_medium_10_30
    params:
      fast_period: 10
      slow_period: 30
      stop_loss_pct: 1.5
      
  - type: ma_crossover
    name: ma_slow_20_50
    params:
      fast_period: 20
      slow_period: 50
      stop_loss_pct: 2.0

# Multiple classifier instances with different parameters
classifiers:
  # Momentum regime classifiers
  - type: momentum_regime_classifier
    name: mom_regime_sensitive
    params:
      rsi_overbought: 65
      rsi_oversold: 35
      momentum_threshold: 0.05
      
  - type: momentum_regime_classifier
    name: mom_regime_balanced
    params:
      rsi_overbought: 70
      rsi_oversold: 30
      momentum_threshold: 0.10
      
  - type: momentum_regime_classifier
    name: mom_regime_stable
    params:
      rsi_overbought: 75
      rsi_oversold: 25
      momentum_threshold: 0.15
      
  # Volatility classifiers  
  - type: volatility_classifier
    name: vol_standard
    params:
      high_vol_threshold: 1.5
      low_vol_threshold: 0.5
      lookback_period: 20
      
  - type: volatility_classifier
    name: vol_wide
    params:
      high_vol_threshold: 2.0
      low_vol_threshold: 0.3
      lookback_period: 30
      
  # Trend classifier
  - type: trend_classifier
    name: trend_standard
    params:
      trend_threshold: 0.02
      fast_ma: 10
      slow_ma: 50

# Execution settings
execution:
  enable_event_tracing: true
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    max_events: 100000
    storage_backend: hierarchical
    use_sparse_storage: true
    batch_size: 5000
    
# Metadata
metadata:
  experiment_id: multi_strategy_grid_v1
  description: |
    Testing multiple strategy and classifier configurations
    to find optimal combinations