# Multi-Strategy Test Configuration
# Tests the new sub-container architecture for multiple strategies

workflow:
  type: "backtest"
  name: "Multi-Strategy Test"

data:
  source: "csv"
  file_path: "data/SPY_1m.csv"
  symbols: ["SPY"]
  max_bars: 50

# Enable comprehensive logging for debugging
logging:
  enabled_events: ["SIGNAL", "ORDER", "FILL", "PORTFOLIO", "TRADE_LOOP"]

strategies:
  - name: "momentum_strategy"
    type: "momentum"
    enabled: true
    allocation: 0.6
    weight: 1.0
    parameters:
      lookback_period: 20
      rsi_period: 14
      rsi_oversold: 40  # More sensitive (was 45)
      rsi_overbought: 60  # More sensitive (was 55)  
      momentum_threshold: 0.0001  # More sensitive (was 0.0002)
  
  - name: "mean_reversion_strategy"
    type: "mean_reversion"
    enabled: true
    allocation: 0.4
    weight: 0.8
    parameters:
      lookback_period: 15
      entry_threshold: 0.8  # More sensitive (was 1.0)
      exit_threshold: 0.2   # More sensitive (was 0.5)

signal_aggregation:
  method: "weighted_voting"
  min_confidence: 0.5

risk:
  initial_capital: 100000
  position_sizers:
    - name: "fixed_size"
      type: "fixed"
      size: 1000  # Much smaller position size to test risk limits
  limits:
    - type: "position"
      max_position: 5000
    - type: "exposure"
      max_exposure_pct: 80

backtest:
  initial_capital: 100000
  commission:
    type: "fixed"
    value: 1.0
  currency: "USD"

output:
  path: "results/multi_strategy_test/"
  generate_report: true