# Multi-Strategy Test Configuration with Proper Container Nesting
# Tests the nested container architecture: Risk > Portfolio > Strategy

workflow:
  type: "backtest"
  name: "Multi-Strategy Nested Test"

data:
  source: "csv"
  file_path: "data/SPY_1m.csv"
  symbols: ["SPY"]
  max_bars: 50

# Enable comprehensive logging for debugging
logging:
  enabled_events: ["SIGNAL", "ORDER", "FILL", "PORTFOLIO", "TRADE_LOOP"]

# Strategy configurations will be nested under portfolio
strategies:
  - name: "momentum_strategy"
    type: "momentum"
    enabled: true
    allocation: 0.6
    weight: 1.0
    parameters:
      lookback_period: 20
      rsi_period: 14
      rsi_oversold: 40
      rsi_overbought: 60
      momentum_threshold: 0.0001
  
  - name: "mean_reversion_strategy"
    type: "mean_reversion"
    enabled: true
    allocation: 0.4
    weight: 0.8
    parameters:
      lookback_period: 15
      entry_threshold: 0.8
      exit_threshold: 0.2

signal_aggregation:
  method: "weighted_voting"
  min_confidence: 0.5

# Risk container configuration
risk:
  initial_capital: 100000
  position_sizers:
    - name: "fixed_size"
      type: "fixed"
      size: 1000
  limits:
    - type: "position"
      max_position: 5000
    - type: "exposure"
      max_exposure_pct: 80

# Portfolio configuration (will be nested under risk)
portfolio:
  initial_capital: 100000

backtest:
  initial_capital: 100000
  commission:
    type: "fixed"
    value: 1.0
  currency: "USD"

output:
  path: "results/multi_strategy_nested_test/"
  generate_report: true