# Multi-Strategy Backtest using EVENT_FLOW_ARCHITECTURE
# Tests multiple strategies and risk profiles simultaneously
# This will create 3 strategies × 3 risk profiles = 9 portfolio containers

backtest:
  name: "Multi-Strategy Test"
  mode: "backtest"
  
  # Data configuration
  data:
    symbols: ["SPY"]
    start_date: "2023-01-01"
    end_date: "2023-12-31"
    source: "csv"
    
  # Feature configuration
  features:
    indicators:
      - name: "sma_20"
        type: "sma"
        period: 20
      - name: "sma_50"
        type: "sma" 
        period: 50
      - name: "rsi"
        type: "rsi"
        period: 14
  
  # Multiple strategies to test
  strategies:
    - type: "momentum"
      name: "conservative_momentum"
      sma_period: 20
      rsi_threshold_long: 30    # More conservative (truly oversold)
      rsi_threshold_short: 70   # More conservative (truly overbought)
      
    - type: "momentum" 
      name: "aggressive_momentum"
      sma_period: 20
      rsi_threshold_long: 45    # Less conservative
      rsi_threshold_short: 55   # Less conservative
      
    - type: "momentum"
      name: "fast_momentum"
      sma_period: 10           # Faster signals
      rsi_threshold_long: 35   
      rsi_threshold_short: 65
      
  # Multiple risk profiles
  risk_profiles:
    - type: "conservative"
      name: "low_risk"
      max_position_percent: 0.05  # 5% max per position
      max_position_value: 25000
      max_drawdown: 0.10
      base_position_percent: 0.01
      
    - type: "moderate"
      name: "med_risk"
      max_position_percent: 0.10  # 10% max per position
      max_position_value: 50000
      max_drawdown: 0.15
      base_position_percent: 0.02
      
    - type: "aggressive"
      name: "high_risk"
      max_position_percent: 0.20  # 20% max per position
      max_position_value: 100000
      max_drawdown: 0.25
      base_position_percent: 0.05
      
  # Execution configuration
  execution:
    fill_probability: 1.0
    partial_fill_probability: 0.0
    random_seed: 42
    slippage:
      base: 0.0001
      volume_factor: 0.00001
      random_factor: 0.0001
    commission:
      per_share: 0.01
      minimum: 1.0
      maximum: 10.0
      
  # Portfolio configuration
  portfolio:
    initial_capital: 100000
    
  # Output configuration
  output:
    results_dir: "./results/multi_strategy_test"
    save_trades: true
    save_metrics: true