# Multi-Strategy Test Configuration with Event Communication Adapters
# Fixes circular dependency issues using pipeline adapter

workflow:
  type: "backtest"
  name: "Multi-Strategy Test (Fixed)"

# Communication configuration to prevent circular dependencies
communication:
  # Use pipeline adapter for linear event flow
  adapters:
    - name: "main_pipeline"
      type: "pipeline"
      containers: [
        "data_container",
        "indicator_container",
        "strategy_container",  # Multi-strategy container
        "risk_container",
        "portfolio_container",
        "execution_container"
      ]
      buffer_size: 1000
      batch_size: 100

data:
  source: "csv"
  file_path: "data/SPY_1m.csv"
  symbols: ["SPY"]
  max_bars: 100

# Enable comprehensive logging for debugging
logging:
  enabled_events: ["SIGNAL", "ORDER", "FILL", "PORTFOLIO", "TRADE_LOOP"]
  # Add communication event logging
  communication:
    log_level: "DEBUG"
    log_event_flow: true
    track_correlation_ids: true

strategies:
  - name: "momentum_strategy"
    type: "momentum"
    enabled: true
    allocation: 0.6
    weight: 1.0
    parameters:
      lookback_period: 20
      rsi_period: 14
      rsi_oversold: 40  # More sensitive (was 45)
      rsi_overbought: 60  # More sensitive (was 55)  
      momentum_threshold: 0.0001  # More sensitive (was 0.0002)
      signal_cooldown: 60  # 1 minute cooldown for testing (was 300s)
  
  - name: "mean_reversion_strategy"
    type: "mean_reversion"
    enabled: true
    allocation: 0.4
    weight: 0.8
    parameters:
      lookback_period: 15
      entry_threshold: 0.8  # More sensitive (was 1.0)
      exit_threshold: 0.2   # More sensitive (was 0.5)

signal_aggregation:
  method: "weighted_voting"
  min_confidence: 0.5

risk:
  initial_capital: 100000
  position_sizers:
    - name: "fixed_size"
      type: "fixed"
      size: 5000  # Smaller position size for multi-strategy
  limits:
    - type: "position"
      max_position: 5000
    - type: "exposure"
      max_exposure_pct: 80

backtest:
  initial_capital: 100000
  commission:
    type: "fixed"
    value: 1.0
  currency: "USD"

output:
  path: "results/multi_strategy_test_fixed/"
  generate_report: true