name: optimize_keltner_gradient
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"
dataset: train
split_ratio: 0.8

# Systematic exploration around the winning parameters (period=50, mult=1.0)
parameter_space:
  strategies:
    # Fine-grained exploration of multipliers around 1.0
    - type: keltner_bands
      param_overrides:
        period: [50]
        multiplier: [0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3]
    
    # Fine-grained exploration of periods around 50
    - type: keltner_bands
      param_overrides:
        period: [35, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 65]
        multiplier: [1.0]
    
    # 2D grid search around optimal point
    - type: keltner_bands
      param_overrides:
        period: [45, 47, 50, 53, 55]
        multiplier: [0.9, 0.95, 1.0, 1.05, 1.1]
    
    # Test if even tighter bands work
    - type: keltner_bands
      param_overrides:
        period: [40, 45, 50, 55, 60]
        multiplier: [0.5, 0.6, 0.7, 0.8]
    
    # Test asymmetric bands (different multipliers for upper/lower)
    # Since we can't do this directly, test various static multipliers
    # to understand which direction benefits from tighter/wider bands
    - type: keltner_bands
      param_overrides:
        period: [50]
        multiplier: [0.85, 0.875, 0.9, 0.925, 0.95, 0.975, 1.0, 1.025, 1.05, 1.075, 1.1, 1.125, 1.15]
      filter: |
        signal == 0 or 
        (signal > 0)  # Long only
    
    - type: keltner_bands
      param_overrides:
        period: [50]
        multiplier: [0.85, 0.875, 0.9, 0.925, 0.95, 0.975, 1.0, 1.025, 1.05, 1.075, 1.1, 1.125, 1.15]
      filter: |
        signal == 0 or 
        (signal < 0)  # Short only

data:
  type: file
  config:
    file_pattern: "./data/{symbol}.csv"
    
timeframe: "1m"

signal_persistence: 
  enabled: true
  compression: sparse

# This will help us understand:
# 1. How sensitive performance is to small parameter changes
# 2. Whether we can get more trades with similar edge by slight adjustments
# 3. If there's a better optimum nearby
# 4. Whether long/short sides behave differently