# Signal Replay Example Configuration
# Demonstrates replaying pre-computed signals with risk parameter overrides

name: signal_replay_example
symbols: ["SPY"]
initial_capital: 100000

# Strategy configurations - must match what was used in signal generation
strategy: [
  {
    sma_crossover: {fast_period: 15, slow_period: 50},
    # Original risk params (what was used during signal generation)
    risk: {
      stop_loss: 0.002,
      take_profit: 0.004
    }
  }
]

# Risk overrides for this replay run
# These will be applied by the portfolio during replay
risk: {
  stop_loss: 0.001,   # Tighter stop loss
  take_profit: 0.006  # Wider take profit
}

# Optional: specify traces directory (defaults to ./traces)
# traces_dir: ./my_traces

# Optional: execution configuration
execution: {
  commission: 0.0001,
  slippage: 0.0001
}