name: "Simple Strategy Test"
description: "Test simple RSI strategy to verify strategy execution works"

symbols: ["SPY"]
data:
  source: "local"
  timeframe: "1m"
  start_date: "2024-03-26"
  end_date: "2024-03-28"

strategies:
  - type: rsi_strategy
    name: simple_rsi
    params:
      rsi_period: 14
      entry_rsi_oversold: 30
      entry_rsi_overbought: 70

mode: signal_generation

execution:
  enable_event_tracing: false
  trace_settings:
    storage_backend: memory