# Simple backtest configuration for testing
# No code required - just configuration!

name: Simple MA Crossover Test
type: backtest
description: Test basic moving average crossover strategy

# Data configuration
data:
  source: csv  # Use CSV data loader
  file_path: "data/SPY_1m.csv"  # Use existing data file
  max_bars: 50  # Limit to 50 bars for testing

# Portfolio configuration
portfolio:
  initial_capital: 100000
  currency: USD
  commission:
    type: fixed
    value: 1.0  # $1 per trade

# Strategy configuration
strategies:
  - name: simple_momentum
    type: momentum
    enabled: true
    allocation: 1.0  # 100% allocation
    parameters:
      lookback_period: 20
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70

# Risk management
risk:
  position_sizers:
    - name: fixed_size
      type: fixed
      size: 10000  # $10k per position
  
  limits:
    - type: position
      max_position: 10000  # Max $10k per position
    - type: exposure
      max_exposure_pct: 100  # Can be fully invested

# Analysis configuration
analysis:
  metrics:
    - total_return
    - sharpe_ratio
    - max_drawdown
  save_results: true
  output_format: json