# Single Ensemble Test - Only the default ensemble
name: single_ensemble_test
description: Test single adaptive ensemble strategy

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data
start_date: "2024-03-26"
end_date: "2025-01-17"

# Topology 
topology: signal_generation

# Classifier configuration
classifiers:
  - type: volatility_momentum_classifier
    name: vol_mom_classifier
    params:
      vol_threshold: 1.6
      rsi_overbought: 65
      rsi_oversold: 40
      atr_period: 14
      rsi_period: 14
      sma_period: 20

# Single ensemble strategy - uses DEFAULT_REGIME_STRATEGIES
strategies:
  - type: duckdb_ensemble
    name: adaptive_ensemble_default
    params:
      classifier_name: volatility_momentum_classifier
      aggregation_method: equal_weight
      min_agreement: 0.33  # At least 33% of strategies must agree (4/12)
      atr_period: 14
      rsi_period: 14
      sma_period: 20
      # Uses DEFAULT_REGIME_STRATEGIES from duckdb_ensemble.py

# Execution settings
execution:
  enable_event_tracing: false
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    storage_backend: memory
    use_sparse_storage: true
    
# Metadata
metadata:
  experiment_id: single_ensemble_test_v1
  description: Single ensemble test to verify regime switching behavior