name: "Single Working Strategy Test"
description: "Test one strategy that works in grid search"

symbols: ["SPY"]
data:
  source: "local"
  timeframe: "1m"
  start_date: "2024-03-26"
  end_date: "2024-03-28"

# Copy exact working strategy from complete_grid_search.yaml
strategies:
  - type: stochastic_rsi
    name: stochastic_rsi_test
    params:
      rsi_period: [7]
      stoch_period: [7] 
      oversold: [15]
      overbought: [80]

mode: signal_generation

execution:
  enable_event_tracing: false
  trace_settings:
    storage_backend: memory