name: test_keltner_with_rsi
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"
dataset: train

# Define RSI feature that we need for the filter
feature_configs:
  rsi_14:
    type: rsi
    period: 14

strategies:
  - name: keltner_rsi_50
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal != 0 and rsi(14) < 50"

data:
  type: file
  config:
    file_pattern: "./data/{symbol}.csv"
    
timeframe: "1m"

signal_persistence: 
  enabled: true
  compression: sparse