# Test Bollinger Bands with EOD closure
name: test_bb_eod
mode: signal_generation
symbols: ["SPY"]
timeframe: "5m"

# Data configuration
data:
  - type: file
    symbols: ["SPY"]
    timeframe: "5m"

# Strategy configuration  
strategy:
  bollinger_bands:
    period: 20
    std_dev: 2.0

# Run with full dataset to test EOD
# python main.py --config config/test_bb_eod.yaml --signal-generation --close-eod