# Full backtest configuration for BB RSI Dependent strategy
dataset:
  name: "train"
  symbols: ["SPY"]
  start_date: "2023-01-01"
  end_date: "2024-01-01"

# Feature configuration
features:
  bollinger_bands:
    type: bollinger_bands
    params:
      period: 20
      std_dev: 2.0
  
  rsi:
    type: rsi
    params:
      period: 14
  
  bb_rsi_dependent:
    type: bb_rsi_dependent
    params:
      lookback: 20
      rsi_divergence_threshold: 5.0
      confirmation_bars: 10
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14

# Strategy configuration
strategies:
  bollinger_rsi_dependent:
    type: bollinger_rsi_dependent
    params:
      exit_at_middle_band: true

# Risk configuration
risk:
  position_size_method: fixed
  fixed_position_size: 0.1
  max_positions: 5
  stop_loss: 0.02
  max_drawdown: 0.20

# Execution configuration  
execution:
  engine_type: synchronous
  commission_rate: 0.001
  slippage_rate: 0.0005
  
# Backtest configuration
backtest:
  initial_capital: 100000
  allow_shorting: true