# Test self-contained Bollinger RSI Divergence
name: test_self_contained
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

# Strategy configuration
strategy:
  bollinger_rsi_self_contained:
    params: {}

# Run with:
# python main.py --config config/test_self_contained.yaml --signal-generation --bars 50000