# Test with a simple moving average strategy
name: test_simple_ma
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-10-01"
end_date: "2024-10-31"

# Test with a simpler strategy that we know works
strategy:
  ma_crossover:
    params:
      fast_period: 10
      slow_period: 20