name: test_keltner_reasonable_filter
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"
dataset: train

# Use strategies list format which supports filters
strategies:
  - name: keltner_filtered_reasonable
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal != 0 and rsi(14) < 70"  # Much more reasonable threshold

# Features needed for filter
features:
  - name: rsi
    params: {period: 14}

# Data source
data:
  type: file
  config:
    file_pattern: "./data/{symbol}.csv"
    
timeframe: "1m"

signal_persistence: 
  enabled: true
  compression: sparse