name: test_keltner_5min
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-03-26"
end_date: "2024-06-30"
dataset: train

# Define all features needed for filters
feature_configs:
  rsi_14:
    type: rsi
    period: 14
  atr_14:
    type: atr
    period: 14
  volume_ratio_20:
    type: volume_ratio
    period: 20
  volatility_percentile_50:
    type: volatility_percentile
    period: 50
  vwap_distance:
    type: vwap_distance

# Test on 5-minute timeframe
strategies:
  # Baseline - no filter
  - name: kb5_baseline
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
      
  # RSI filter - proper exit handling
  - name: kb5_rsi70
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal == 0 or rsi(14) < 70"
    
  # RSI filter - more restrictive
  - name: kb5_rsi50
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal == 0 or rsi(14) < 50"
    
  # Directional RSI
  - name: kb5_directional
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal == 0 or (signal > 0 and rsi(14) < 40) or (signal < 0 and rsi(14) > 60)"
    
  # Volume + RSI combo
  - name: kb5_volume_rsi
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal == 0 or (rsi(14) < 60 and volume_ratio(20) > 1.2)"
    
  # High volatility only
  - name: kb5_high_vol
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0
    filter: "signal == 0 or volatility_percentile(50) > 0.7"
    
  # Optimized parameters with filter
  - name: kb5_opt_params
    type: keltner_bands
    params:
      period: 15
      multiplier: 1.8
    filter: "signal == 0 or (rsi(14) < 65 and volume_ratio(20) > 1.1)"

data:
  type: file
  config:
    file_pattern: "./data/{symbol}.csv"
    
timeframe: "5m"

signal_persistence: 
  enabled: true
  compression: sparse