# Minimal test configuration for signal filtering
name: test_filter_minimal
mode: backtest
symbols: ["SPY"]
start_date: "2024-01-01" 
end_date: "2024-01-05"
initial_capital: 100000

# Single strategy with simple filter
strategies:
  - name: sma_test
    type: sma_crossover
    params:
      fast_period: 5
      slow_period: 10
    filter: "signal > 0"  # Only accept long signals

# Features
features:
  - sma