# Test parameter expansion with explicit strategy definitions
name: "Parameter Expansion Signal Generation Test - Explicit"

data:
  symbols: ['SPY']
  source: 'csv'
  start_date: '2024-01-01'
  end_date: '2024-12-31'

symbols: ['SPY']
timeframes: ['1m']
max_bars: 100  # More data for better testing

# Explicitly define each parameter combination as a separate strategy
strategies:
  # Fast 5 combinations
  - name: 'ma_5_20'
    type: 'ma_crossover'
    params:
      fast_period: 5
      slow_period: 20
      
  - name: 'ma_5_30'
    type: 'ma_crossover'
    params:
      fast_period: 5
      slow_period: 30
      
  - name: 'ma_5_50'
    type: 'ma_crossover'
    params:
      fast_period: 5
      slow_period: 50
      
  # Fast 10 combinations
  - name: 'ma_10_20'
    type: 'ma_crossover'
    params:
      fast_period: 10
      slow_period: 20
      
  - name: 'ma_10_30'
    type: 'ma_crossover'
    params:
      fast_period: 10
      slow_period: 30
      
  - name: 'ma_10_50'
    type: 'ma_crossover'
    params:
      fast_period: 10
      slow_period: 50
      
  # Fast 20 combinations
  - name: 'ma_20_30'
    type: 'ma_crossover'
    params:
      fast_period: 20
      slow_period: 30
      
  - name: 'ma_20_50'
    type: 'ma_crossover'
    params:
      fast_period: 20
      slow_period: 50

execution:
  max_duration: 0.0
  enable_event_tracing: true
  trace_settings:
    use_sparse_storage: true
    enable_console_output: false
    container_settings:
      'strategy*':
        enabled: true
      'data*':
        enabled: false  # Don't trace data containers
      'portfolio*':
        enabled: false  # Signal generation doesn't need portfolio

metadata:
  workflow_id: 'parameter_expansion_explicit_test'
  experiment_type: 'signal_generation'
  notes: 'Testing with 8 explicit MA crossover combinations'

# Use the signal generation topology
topology: 'signal_generation'