# Test root container only - absolute minimal config
# This creates just the root coordinator container

name: root_container_test

# Workflow with minimal backtest
workflow:
  type: simple_backtest
  phases:
    - name: test_phase

# Execution mode
execution:
  mode: backtest
  enable_event_tracing: true
  trace_settings:
    default_retention: full  # Full tracing to see everything
    max_events: 10000
    trace_dir: './traces'

# Minimal data config
data:
  symbols: ['SPY']
  start_date: '2024-01-01'
  end_date: '2024-01-02'
  max_bars: 0  # No data loading

# Minimal portfolio
portfolio:
  initial_capital: 100000

# Minimal strategy to satisfy validation
strategies:
  - name: test_strategy
    type: momentum
    enabled: false  # Disabled so it won't actually trade
    allocation: 1.0
    config:
      fast_period: 10
      slow_period: 20

# Results storage
results:
  retention_policy: full
  max_events: 10000