# Test a smaller subset of mean reversion strategies
name: test_mean_reversion_small
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Base strategy (used when not optimizing)
strategy:
  rsi_bands:
    params:
      rsi_period: 14
      oversold: 30
      overbought: 70

# Test just a few specific strategies instead of wildcard
parameter_space:
  indicators:
    mean_reversion: "*"
    # Limit to just these 2 strategies
    include: ["rsi_bands", "bollinger_bands"]
    
    # Override parameters to reduce combinations
    param_overrides:
      rsi_bands:
        rsi_period: [10, 14, 20]  # Just 3 values instead of full range
        oversold: [20, 30]        # Just 2 values
        overbought: [70, 80]      # Just 2 values
      bollinger_bands:
        bb_period: [20, 30]       # Just 2 values
        bb_std: [2.0, 2.5]        # Just 2 values
    
# Control optimization granularity
optimization:
  granularity: 2  # Lower = fewer samples for float ranges

# Run with:
# python main.py --config config/test_mean_reversion_small.yaml --signal-generation --optimize --dataset train