# Test configuration for trendline-based strategies
name: trendline_strategies_test
mode: backtest
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"
initial_capital: 100000

# Test trendline strategies
strategy:
  type: ensemble
  strategies:
    # Trendline bounce strategy (mean reversion)
    - name: trendline_bounce
      type: trendline_bounces
      weight: 0.34
      params:
        pivot_lookback: 20
        min_touches: 3
        tolerance: 0.002
        bounce_threshold: 0.003
    
    # Trendline breakout strategy (momentum)
    - name: trendline_break
      type: trendline_breaks
      weight: 0.33
      params:
        pivot_lookback: 20
        min_touches: 2
        tolerance: 0.002
    
    # Pivot channel bounce strategy (mean reversion)
    - name: pivot_bounce
      type: pivot_channel_bounces
      weight: 0.33
      params:
        sr_period: 20
        min_touches: 2
        bounce_threshold: 0.002

# Common strategy settings
weight_threshold: 0.5

# Data configuration
data:
  storage_type: arctic
  arctic_uri: mongodb://localhost:27017/
  data_type: bars
  universe_name: us_stocks
  timeframes: ["5m"]

# Execution settings
execution:
  mode: vectorized
  max_positions: 1
  position_size: 0.95

# Risk management
risk:
  stop_loss: 0.02  # 2% stop loss
  take_profit: 0.04  # 4% take profit

# Output settings
output:
  results_dir: results/trendline_test
  save_signals: true
  save_metrics: true
  save_trades: true
  log_level: debug