# Test intraday threshold for EOD closure
name: test_intraday_threshold
mode: signal_generation
symbols: ["SPY"]

# Strategy with intraday threshold
strategy: [
  {
    bollinger_bands: {
      period: 20,
      std_dev: 2.0
    },
    threshold: "intraday"
  }
]

# Run with:
# python main.py --config config/test_intraday_threshold.yaml --signal-generation