name: test_simple_keltner
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-06-30"

strategies:
  - name: kb_test
    type: keltner_bands
    params:
      period: 20
      multiplier: 2.0

data:
  type: file
  config:
    file_pattern: "./data/{symbol}.csv"
    
timeframe: "1m"

signal_persistence: 
  enabled: true
  compression: sparse