# Test bar streaming with 10 bars
# Based on single container test but with actual data streaming

name: bar_streaming_test

# Workflow
workflow:
  type: simple_backtest
  phases:
    - name: test_phase
      topology: root_backtest  # Use root container topology

# Execution config
execution:
  mode: backtest
  enable_event_tracing: true
  trace_settings:
    storage_backend: hierarchical  # Use workspace structure
    auto_flush_on_cleanup: true    # Auto-flush traces to disk (default: true)
    default_retention: full
    max_events: 1000
    enable_console_output: true
    console_filter: ['BAR', 'SIGNAL', 'FILL', 'ORDER', 'POSITION_OPEN', 'POSITION_CLOSE']
    container_settings:
      '*': # All containers
        enabled: true
        max_events: 1000

# Data config
data:
  symbols: ['SPY']
  timeframes: ['1m']  # We have 1-minute data
  start_date: '2024-01-01'
  end_date: '2024-01-15'  # About 10 trading days

# Minimal portfolio (required by validation)
portfolio:
  initial_capital: 100000

# No strategies (allowed now)
strategies: []

# Results
results:
  retention_policy: full
  max_events: 1000