# Test Configuration for ComponentState - Strategies + Classifiers
# Demonstrates unified component execution without specialized events

name: component_state_test
description: Test ComponentState with both strategies and classifiers

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data
start_date: "2023-01-01"
end_date: "2023-02-01"
max_bars: 100

# Topology pattern 
topology_pattern: signal_generation

# Feature configuration for both strategies and classifiers  
feature_configs:
  sma_20:
    feature: sma
    period: 20
  rsi:
    feature: rsi
    period: 14
  macd:
    feature: macd
    fast: 12
    slow: 26
    signal: 9
  momentum:
    feature: momentum
    periods: [10, 20]

# Strategy configuration (legacy format - backward compatibility)
strategies:
  - type: simple_momentum
    params:
      sma_period: 20
      rsi_threshold_long: 30
      rsi_threshold_short: 70
      exit_bars: 5

# Classifier configuration (for topology pattern)
classifiers:
  - type: momentum_regime_classifier
    params:
      rsi_overbought: 70
      rsi_oversold: 30
      momentum_threshold: 0.10  # Increased from 0.02 to reduce noise

# Execution configuration
execution:
  enable_event_tracing: true
  trace_settings:
    events_to_trace: ["SIGNAL"]  # Only trace outputs
    max_events: 10000
    storage_backend: hierarchical
    use_sparse_storage: true
    batch_size: 1000

# Test metadata
metadata:
  workflow_id: component_test
  phase_name: unified_execution