# Test signal generation with simple MA crossover
name: test_signal_generation

# Use signal generation workflow
workflow:
  type: simple_backtest
  phases:
    - name: signal_gen
      topology: signal_generation  # Use signal generation topology

# Execution config
execution:
  mode: signal_generation
  enable_event_tracing: true
  trace_settings:
    storage_backend: hierarchical
    auto_flush_on_cleanup: true
    default_retention: full
    max_events: 10000
    enable_console_output: true
    console_filter: ['BAR', 'SIGNAL', 'FEATURE']
    container_settings:
      '*':
        enabled: true
        max_events: 10000

# Data config
data:
  symbols: ['SPY']
  timeframes: ['1m']
  start_date: '2024-01-01'
  end_date: '2024-01-02'  # Just 1 day for testing
  max_bars: 100  # Limit bars for quick test

# Required config for signal generation topology
symbols: ['SPY']
timeframes: ['1m']
data_source: file
data_path: './data'
data_dir: './data'
start_date: '2024-01-01'
end_date: '2024-01-02'
max_bars: 100

# Simple momentum strategy - topology builder should infer features
strategies:
  - name: ma_crossover
    type: momentum
    params:
      sma_period: 5
    symbols: ['SPY']

# Strategy names for portfolio containers (signal collection)
strategy_names: ['ma_crossover']

# Portfolio config (required by schema)
portfolio:
  initial_capital: 100000
  max_allocation: 1.0

# Signal save directory
signal_save_directory: './results/signals/'

# Results
results:
  retention_policy: full
  max_events: 10000