# Empty topology test - minimal configuration with no components
# Testing incremental topology building starting from zero

name: empty_topology_test

# Workflow
workflow:
  type: simple_backtest
  phases:
    - name: test_phase

# Execution config with full tracing
execution:
  mode: backtest
  enable_event_tracing: true
  trace_settings:
    default_retention: full
    max_events: 1000
    trace_dir: './traces'

# Minimal data config - no symbols
data:
  symbols: []  # Empty symbols list
  start_date: '2024-01-01'
  end_date: '2024-01-02'

# Minimal portfolio
portfolio:
  initial_capital: 100000

# No strategies
strategies: []

# Results
results:
  retention_policy: full
  max_events: 1000