# Test MA crossover signal generation and storage
# Verify signals are being stored in portfolio containers

name: ma_crossover_storage_test

# Workflow
workflow:
  type: simple_backtest
  phases:
    - name: test_phase
      topology: signal_generation  # Use the signal generation topology

# Execution config
execution:
  mode: signal_generation
  enable_event_tracing: true
  trace_settings:
    storage_backend: hierarchical  # Use hierarchical storage for proper organization
    auto_flush_on_cleanup: true    
    default_retention: full
    max_events: 1000
    enable_console_output: true
    console_filter: ['BAR', 'SIGNAL']  # Focus on BAR and SIGNAL events
    container_settings:
      portfolio_*:  # Ensure portfolio containers have tracing enabled
        enabled: true
        max_events: 1000
      strategy_*:   # Ensure strategy containers have tracing enabled
        enabled: true
        max_events: 1000

# Data config - use limited data to verify flow
data:
  symbols: ['SPY']
  timeframes: ['1m']

# These need to be at top level for signal_generation topology
symbols: ['SPY']
timeframes: ['1m']

# Simple strategy using ma_crossover
strategies:
  - name: ma_crossover
    type: ma_crossover  # Use the ma_crossover strategy we fixed
    params:
      fast_period: 5
      slow_period: 10

# Portfolio configuration (required)
portfolio:
  initial_capital: 100000
  managed_strategies: ['ma_crossover']  # Tell portfolio to manage this strategy

# Results
results:
  retention_policy: full
  max_events: 1000

# Override max_bars for quick test
max_bars: 20  # Just stream 20 bars to verify