name: test_notebook
data: SPY_5m

strategy: [
  {
    bollinger_bands: {
      period: 20,
      std_dev: 2.0
    }
  }
]

# Use specific parameters to avoid combo_id issue
results:
  save_trades: true
  save_metrics: true