# Test bar streaming with momentum strategy signals
# Based on test_bar_streaming.yaml but with signal generation

name: bar_streaming_with_signals_test

# Workflow
workflow:
  type: simple_backtest
  phases:
    - name: test_phase
      topology: backtest  # Use full backtest topology with strategies

# Execution config
execution:
  mode: backtest
  enable_event_tracing: true
  trace_settings:
    storage_backend: hierarchical  # Use workspace structure
    auto_flush_on_cleanup: true    # Auto-flush traces to disk (default: true)
    default_retention: full
    max_events: 1000
    enable_console_output: true
    console_filter: ['BAR', 'SIGNAL', 'FILL', 'ORDER', 'POSITION_OPEN', 'POSITION_CLOSE']
    container_settings:
      '*': # All containers
        enabled: true
        max_events: 1000

# Data config
data:
  symbols: ['SPY']
  timeframes: ['1m']  # We have 1-minute data
  start_date: '2024-01-01'
  end_date: '2024-01-15'  # About 10 trading days

# Required for backtest topology
symbols: ['SPY']
timeframes: ['1m']
data_source: file
data_path: './data'
start_date: '2024-01-01'
end_date: '2024-01-15'
initial_capital: 100000

# Portfolio (required by validation)
portfolio:
  initial_capital: 100000

# Add a simple momentum strategy
strategies:
  - name: momentum_test
    type: momentum_strategy
    params:
      sma_period: 5  # Short period for quick signals with limited data
      rsi_threshold_long: 40   # More relaxed thresholds
      rsi_threshold_short: 60
    symbols: ['SPY']

# Results
results:
  retention_policy: full
  max_events: 1000