# Test single mean reversion strategy
name: test_single_mean_reversion
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Single strategy without optimization
strategy:
  bollinger_bands:
    params:
      period: 20
      std_dev: 2.0

# Run with:
# python main.py --config config/test_single_mean_reversion.yaml --signal-generation --bars 100