# Test configuration for MA crossover strategy (best momentum performer)
# Based on regime analysis showing 35% annualized return in strong momentum

symbols:
  - SPY

timeframes:
  - 1m

data_source: file
data_dir: ./data
dataset: test  # Use same out-of-sample test data
split_ratio: 0.8

# MA Crossover strategy with best performing parameters from regime analysis
strategies:
  - name: ma_crossover_momentum_test
    type: ma_crossover
    params:
      fast_period: 5          # Best performer: 5_100_2.0  
      slow_period: 100        # Fixed parameter names to match strategy
      signal_threshold: 2.0   # 2.0% threshold for signal confirmation

# Execution settings
execution:
  enable_event_tracing: false
  trace_settings:
    events_to_trace: ["SIGNAL"]
    storage_backend: memory
    use_sparse_storage: true
    enable_console_output: false

# Store results
results:
  streaming_metrics: true
  results_storage: disk
  output_dir: ./results/ma_crossover_momentum_test