# Test config for Bollinger RSI Divergence Exact
name: test_bb_rsi_exact
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Strategy configuration
strategy:
  bollinger_rsi_divergence_exact:
    params: {}

# Run with:
# python main.py --config config/test_bb_rsi_exact.yaml --signal-generation --bars 5000