# Single container test - absolutely minimal
# Just create one data container and verify lifecycle

name: single_container_test

# Workflow
workflow:
  type: simple_backtest
  phases:
    - name: test_phase
      topology: root_backtest  # Use root container topology

# Execution config
execution:
  mode: backtest
  enable_event_tracing: true
  trace_settings:
    default_retention: full
    max_events: 1000
    trace_dir: './traces'

# Single symbol to create one data container
data:
  symbols: ['SPY']
  timeframes: ['1d']
  start_date: '2024-01-01'
  end_date: '2024-01-02'
  max_bars: 0  # No data loading

# Minimal portfolio (required by validation)
portfolio:
  initial_capital: 100000

# No strategies (allowed now)
strategies: []

# Results
results:
  retention_policy: full
  max_events: 1000