# Enhanced Debug Configuration for Two-Layer Ensemble
# Using the actual strategy configuration from the test workspace

name: two_layer_enhanced_debug_full
description: Enhanced debug with full strategy set from test workspace

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data

# Topology 
topology: signal_generation

# Classifier configuration - using the actual SPY_market_regime_grid_0006_12
classifiers:
  - type: market_regime_classifier
    name: SPY_market_regime_grid_0006_12
    params:
      trend_threshold: 0.006
      vol_threshold: 0.8
      sma_short: 12
      sma_long: 20
      atr_period: 14
      rsi_period: 14

# Enhanced debug ensemble with full strategy set
strategies:
  - type: two_layer_ensemble_enhanced_debug
    name: baseline_plus_regime_boosters
    params:
      classifier_name: market_regime_classifier
      baseline_allocation: 0.25   # 25% baseline
      baseline_aggregation: equal_weight
      booster_aggregation: equal_weight
      min_baseline_agreement: 0.2
      min_booster_agreement: 0.2
      
      # Pass classifier params
      trend_threshold: 0.006
      vol_threshold: 0.8
      sma_short: 12
      sma_long: 20
      atr_period: 14
      rsi_period: 14
      
      # Baseline strategies (always active) - from the actual test
      baseline_strategies:
        - name: pivot_channel_bounces
          params: {pivot_period: 5, stop_loss: 0.02, take_profit: 0.02}
        - name: aroon_crossover
          params: {aroon_period: 19}
        - name: stochastic_crossover
          params: {stochastic_k_period: 23, stochastic_d_period: 3}
        - name: roc_trend
          params: {roc_period: 19, roc_threshold: 0.031}
        - name: williams_r
          params: {williams_period: 21, oversold: -80, overbought: -20}
      
      # Regime boosters - from the actual test
      regime_boosters:
        bull_ranging:
          - name: pivot_channel_breaks
            params: {pivot_period: 5}
          - name: bollinger_breakout
            params: {bollinger_period: 15, bollinger_dev: 2.0}
          - name: rsi_bands
            params: {rsi_period: 11, oversold: 20, overbought: 75}
          - name: keltner_mean_reversion
            params: {keltner_period: 17, keltner_multiplier: 1.0}
          - name: stochastic_rsi
            params: {stochastic_k_period: 23, stochastic_d_period: 3, rsi_period: 15}
          - name: support_resistance_breakout
            params: {lookback_period: 33, num_levels: 3, volume_factor: 1.0}
          - name: pivot_channel_breaks
            params: {pivot_period: 15}
          - name: bollinger_mean_reversion
            params: {bollinger_period: 17, bollinger_dev: 1.5}
          - name: roc_threshold
            params: {period: 5, threshold: 0.05}
          - name: ichimoku_cloud_position
            params: {conversion_period: 27, base_period: 33}
          - name: parabolic_sar
            params: {af_start: 0.02, af_increment: 0.02, af_max: 0.2}
          - name: dema_crossover
            params: {fast_dema_period: 19, slow_dema_period: 17}
          - name: chaikin_money_flow
            params: {cmf_period: 21, threshold: 0.08}
          - name: mfi_bands
            params: {mfi_period: 13, oversold: 20, overbought: 75}
          - name: pivot_channel_bounces
            params: {pivot_period: 33, stop_loss: 0.01, take_profit: 0.024}
          - name: ema_sma_crossover
            params: {ema_period: 11, sma_period: 21}
          - name: obv_trend
            params: {obv_period: 13}
            
        bear_ranging:
          - name: adx_trend_strength
            params: {adx_period: 25, adx_threshold: 28, di_threshold: 21}
          - name: ema_sma_crossover
            params: {ema_period: 11, sma_period: 23}
          - name: rsi_bands
            params: {rsi_period: 15, oversold: 25, overbought: 80}
          - name: vortex_crossover
            params: {vortex_period: 21}
          - name: dema_sma_crossover
            params: {dema_period: 19, sma_period: 15}
          - name: rsi_threshold
            params: {period: 21, threshold: 50}
          - name: supertrend
            params: {period: 23, multiplier: 3.0}
          - name: vwap_deviation
            params: {std_dev: 3.0}
          - name: trendline_bounces
            params: {lookback_period: 17, touch_threshold: 0.002, angle_threshold: 0.04}
          - name: linear_regression_slope
            params: {lr_period: 23, slope_threshold: 0.045}
          - name: fibonacci_retracement
            params: {lookback_period: 25, fib_level: 0.618}
          - name: tema_sma_crossover
            params: {tema_period: 5, sma_period: 23}
          - name: cci_bands
            params: {cci_period: 17, oversold: -105, overbought: 100}
          - name: elder_ray
            params: {ema_period: 17, threshold: 0.09}
          - name: macd_crossover
            params: {fast_ema: 5, slow_ema: 35, signal_ema: 9}
          - name: atr_channel_breakout
            params: {atr_period: 17, channel_multiplier: 2.0}
          - name: donchian_breakout
            params: {period: 13}
            
        neutral:
          - name: aroon_oscillator
            params: {aroon_period: 23}
          - name: bollinger_mean_reversion
            params: {bollinger_period: 23, bollinger_dev: 2.5}
          - name: stochastic_rsi
            params: {stochastic_k_period: 15, stochastic_d_period: 5, rsi_period: 23}
          - name: keltner_breakout
            params: {keltner_period: 25, keltner_multiplier: 1.0}
          - name: vortex_trend
            params: {vortex_period: 17, threshold: 1.0}
          - name: keltner_mean_reversion
            params: {keltner_period: 21, keltner_multiplier: 1.0}
          - name: cci_threshold
            params: {cci_period: 19, cci_threshold: 100}
          - name: ultimate_oscillator
            params: {short_period: 3, medium_period: 17, long_period: 25, oversold: 25, overbought: 70}
          - name: price_action_swing
            params: {lookback_bars: 3}
          - name: accumulation_distribution
            params: {ad_period: 19, signal_period: 9}
          - name: trendline_breaks
            params: {lookback_period: 15, min_touches: 3, angle_threshold: 0.03}
          - name: vortex_crossover
            params: {vortex_period: 15}
          - name: ichimoku_cloud_position
            params: {conversion_period: 9, base_period: 35}
          - name: macd_crossover
            params: {fast_ema: 5, slow_ema: 31, signal_ema: 9}
          - name: aroon_crossover
            params: {aroon_period: 19}
          - name: dema_sma_crossover
            params: {dema_period: 19, sma_period: 13}
          - name: williams_r
            params: {williams_period: 21, oversold: -80, overbought: -20}

# Execution settings
execution:
  enable_event_tracing: false
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    storage_backend: memory
    use_sparse_storage: true
    
# Metadata
metadata:
  experiment_id: two_layer_enhanced_debug_full
  description: Full ensemble with enhanced debug to verify all strategies are called