# Two-Layer Ensemble Configuration - Actual Implementation
# This creates ONE ensemble instance, not multiple

name: two_layer_actual
description: Actual two-layer ensemble with single instance

# Data configuration  
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data

# Topology
topology: signal_generation

# Classifier configuration
classifiers:
  - type: market_regime_classifier
    name: market_regime_detector
    params:
      trend_threshold: 0.006
      vol_threshold: 0.8
      sma_short: 12
      sma_long: 20
      atr_period: 14
      rsi_period: 14

# Single ensemble strategy entry
strategies:
  - type: two_layer_ensemble
    name: baseline_plus_regime_boosters
    params:
      classifier_name: market_regime_classifier
      baseline_allocation: 0.25
      baseline_aggregation: equal_weight
      booster_aggregation: equal_weight
      min_baseline_agreement: 0.2
      min_booster_agreement: 0.2
      
      # Pass classifier params
      trend_threshold: 0.006
      vol_threshold: 0.8
      sma_short: 12
      sma_long: 20
      atr_period: 14
      rsi_period: 14
      
      # Baseline strategies (inside the ensemble)
      baseline_strategies:
        - name: pivot_channel_bounces
          params: {pivot_period: 5, stop_loss: 0.02, take_profit: 0.02}
        - name: aroon_crossover
          params: {aroon_period: 19}
        - name: stochastic_crossover
          params: {stochastic_k_period: 23, stochastic_d_period: 3}
        - name: roc_trend
          params: {roc_period: 19, roc_threshold: 0.031}
        - name: williams_r
          params: {williams_period: 21, oversold: -80, overbought: -20}
      
      # Regime boosters
      regime_boosters:
        bull_ranging:
          - name: pivot_channel_breaks
            params: {pivot_period: 5}
          - name: rsi_bands
            params: {rsi_period: 11, oversold: 20, overbought: 75}
          - name: stochastic_rsi
            params: {stochastic_k_period: 23, stochastic_d_period: 3, rsi_period: 15}
          - name: roc_threshold
            params: {period: 5, threshold: 0.05}
          - name: pivot_channel_bounces
            params: {pivot_period: 33, stop_loss: 0.01, take_profit: 0.024}
          
        bear_ranging:
          - name: rsi_threshold
            params: {period: 21, threshold: 50}
          - name: tema_sma_crossover
            params: {tema_period: 5, sma_period: 23}
          - name: macd_crossover
            params: {fast_ema: 5, slow_ema: 35, signal_ema: 9}
          - name: cci_bands
            params: {cci_period: 17, oversold: -105, overbought: 100}
          - name: vortex_crossover
            params: {vortex_period: 21}
            
        neutral:
          - name: stochastic_rsi
            params: {stochastic_k_period: 15, stochastic_d_period: 5, rsi_period: 23}
          - name: cci_threshold
            params: {cci_period: 19, cci_threshold: 100}
          - name: ultimate_oscillator
            params: {short_period: 3, medium_period: 17, long_period: 25, oversold: 25, overbought: 70}
          - name: macd_crossover
            params: {fast_ema: 5, slow_ema: 31, signal_ema: 9}
          - name: williams_r
            params: {williams_period: 21, oversold: -80, overbought: -20}

# Execution settings
execution:
  enable_event_tracing: true
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    storage_backend: parquet
    use_sparse_storage: true
    
# Metadata
metadata:
  experiment_id: two_layer_actual
  description: Actual two-layer ensemble implementation