# Two-Layer Regime-Adaptive Ensemble Configuration
# Architecture: Always-active baseline + regime-specific boosters
# Based on comprehensive analysis of 1,229 strategies

name: two_layer_regime_ensemble
description: Two-layer ensemble with always-active baseline + regime boosters

# Data configuration
symbols: ["SPY"]
timeframes: ["1m"]
data_source: file
data_dir: ./data
start_date: "2024-03-26"
end_date: "2025-01-17"

# Topology 
topology: signal_generation

# Classifier configuration - market regime detection
# Using SPY_market_regime_grid_0006_12 parameters from our analysis
classifiers:
  - type: market_regime_classifier
    name: market_regime_detector
    params:
      # Exact parameters matching SPY_market_regime_grid_0006_12
      trend_threshold: 0.006      # 0.6% threshold (0006 in name)
      vol_threshold: 0.8          # Volatility threshold
      sma_short: 12               # Short SMA period (12 in name)
      sma_long: 50                # Long SMA period
      atr_period: 20              # ATR period for volatility
      rsi_period: 14              # RSI period for momentum

# Two-layer ensemble using custom two_layer_ensemble strategy
strategies:
  - type: two_layer_ensemble
    name: baseline_plus_regime_boosters
    params:
      classifier_name: market_regime_classifier
      baseline_allocation: 0.25   # 25% to always-active baseline
      baseline_aggregation: equal_weight
      booster_aggregation: equal_weight
      min_baseline_agreement: 0.3  # 30% consensus required for baseline
      min_booster_agreement: 0.3   # 30% consensus required for boosters
      
      # Add classifier parameters to resolve feature mapping
      trend_threshold: 0.006
      vol_threshold: 0.8
      sma_short: 12
      sma_long: 50
      atr_period: 20
      rsi_period: 14
      
      # Always-active baseline strategies (cross-regime performers)
      baseline_strategies:
        - name: dema_crossover
          params: {fast_dema_period: 19, slow_dema_period: 15}
        - name: elder_ray
          params: {ema_period: 13, bull_threshold: 0, bear_threshold: -0.001}
        - name: sma_crossover
          params: {fast_period: 19, slow_period: 15}
        - name: stochastic_crossover
          params: {k_period: 5, d_period: 7}
        - name: pivot_channel_bounces
          params: {sr_period: 15, min_touches: 2, bounce_threshold: 0.001}
      
      # Regime-specific boosters (activate only when regime detected)
      regime_boosters:
        bull_ranging:
          - name: roc_threshold
            params: {period: 5, threshold: 0.05}
          - name: rsi_threshold
            params: {period: 27, threshold: 50}
          - name: atr_channel_breakout
            params: {atr_period: 7, channel_period: 30, atr_multiplier: 1.5}
          - name: mfi_bands
            params: {period: 7, oversold: 25, overbought: 85}
            
        bear_ranging:
          - name: trendline_bounces
            params: {lookback: 5, min_touches: 2, threshold: 0.0005, strength: 0.1}
          - name: tema_sma_crossover
            params: {tema_period: 5, sma_period: 23}
          - name: rsi_threshold
            params: {period: 27, threshold: 50}
          - name: macd_crossover
            params: {fast_ema: 5, slow_ema: 35, signal_ema: 9}
            
        neutral:
          - name: ichimoku_cloud_position
            params: {conversion_period: 9, base_period: 35}
          - name: williams_r
            params: {williams_period: 21, oversold: -80, overbought: -20}
          - name: ema_sma_crossover
            params: {ema_period: 5, sma_period: 50}
          - name: aroon_crossover
            params: {period: 14}

# Execution settings
execution:
  enable_event_tracing: false
  trace_settings:
    events_to_trace: ["SIGNAL", "CLASSIFICATION"]
    storage_backend: memory
    use_sparse_storage: true
    
# Metadata
metadata:
  experiment_id: two_layer_regime_ensemble_v1
  expected_return: 8.48%  # From comprehensive analysis
  description: |
    Custom two-layer regime-adaptive ensemble strategy.
    Based on comprehensive analysis of 1,229 strategies and 81 classifiers.
    
    🏗️ Architecture: Perfect Two-Layer Implementation
    
    🌐 Baseline Layer (25% allocation) - Always Active:
    - SPY_dema_crossover_grid_19_15 (13.08% across 3 regimes)
    - SPY_elder_ray_grid_13_0_-0.001 (8.99% across 2 regimes) 
    - SPY_sma_crossover_grid_19_15 (8.68% across 2 regimes)
    - SPY_stochastic_crossover_grid_5_7 (8.34% across 2 regimes)
    - SPY_pivot_channel_bounces_grid_15_2_0.001 (7.99% across 3 regimes)
    
    🎯 Regime Booster Layer (75% allocation) - Conditional:
    - Bull ranging boosters: roc_threshold, rsi_threshold, atr_channel_breakout, mfi_bands
    - Bear ranging boosters: trendline_bounces, tema_sma_crossover, rsi_threshold, macd_crossover
    - Neutral boosters: ichimoku, williams_r, ema_sma_crossover, aroon_crossover
    
    Key features:
    - True two-layer architecture with separate allocation weighting
    - Baseline strategies run continuously (25% weight)
    - Regime boosters activate conditionally (75% weight) 
    - Signal combination logic handles layer conflicts intelligently
    - No strategy type duplicates between layers
    - Robust fallback to neutral regime if classifier fails
    
    Signal aggregation:
    - Each layer uses equal-weight consensus (30% agreement threshold)
    - Final signal combines layers using allocation weighting
    - Conflicting signals resolved by layer strength (allocation × agreement)
    
    Expected performance:
    - Baseline layer provides consistent 9.42% foundation
    - Regime boosters add conditional optimization
    - Total expected return: 8.48% with enhanced stability