# Example YAML-driven backtest configuration
# This file can be run directly without any Python code

mode: backtest

config:
  # Data configuration
  symbols: [SPY]
  timeframes: [5T]
  data_source: file
  data_path: ./data
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  
  # Strategy configuration
  strategies:
    - type: momentum
      name: Fast Momentum
      fast_period: 10
      slow_period: 30
      signal_threshold: 0.02
      
    - type: mean_reversion
      name: Bollinger Reversion
      lookback: 20
      num_std: 2
      entry_threshold: 0.95
  
  # Risk management
  risk_profiles:
    - type: conservative
      name: Low Risk
      max_position_size: 0.1
      max_portfolio_heat: 0.06
      stop_loss: 0.02
      
    - type: moderate
      name: Medium Risk
      max_position_size: 0.2
      max_portfolio_heat: 0.12
      stop_loss: 0.03
  
  # Feature configuration
  features:
    returns:
      periods: [1, 5, 20]
    volume:
      ma_period: 20
      relative: true
    volatility:
      period: 20
      annualize: true
  
  # Execution configuration
  execution:
    commission: 0.001
    slippage: 0.0005
    min_order_size: 100
    
  # Portfolio configuration
  initial_capital: 100000
  
  # Results configuration
  results:
    save_trades: true
    save_metrics: true
    save_equity_curve: true
    output_dir: ./results/backtests/
    
  # Metrics to calculate
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor

# Tracing configuration (optional)
tracing_config:
  enabled: false
  trace_id: yaml_example_001
  trace_dir: ./traces/
  max_events: 10000

# Metadata (optional)
metadata:
  experiment_name: YAML-driven example
  author: ADMF-PC User
  description: Example showing pure YAML configuration
  tags: [example, yaml-driven, backtest]