# Bollinger Band + RSI Divergence (Relaxed) Strategy
name: bollinger_rsi_divergence_relaxed
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-04-01"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14

# Strategy configuration
strategy:
  bollinger_rsi_divergence_relaxed:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_threshold: 10
      lookback: 10