# Bollinger Band + True RSI Divergence Strategy Test
name: bollinger_rsi_true_divergence_test
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-04-01"

# Enable verbose signal output
signal_filters:
  - verbose_signals: true

# Required features
feature_config:
  bollinger_bands:
    - period: 20
      std_dev: 2.0
  rsi:
    - period: 14
  rsi_divergence:
    - rsi_period: 14
      lookback_bars: 30
      min_bars_between: 3
      rsi_divergence_threshold: 3.0
      price_threshold_pct: 0.0005

# Strategy configuration
strategy:
  bollinger_rsi_true_divergence:
    params:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      lookback_bars: 30
      min_bars_between: 3
      rsi_divergence_threshold: 3.0
      price_threshold_pct: 0.0005
      require_band_extreme: false
      exit_at_middle: true