# Parameter optimization configuration
# Find optimal parameters without writing optimization code

name: MA Strategy Parameter Optimization
type: optimization
description: Find optimal moving average periods using Bayesian optimization

# Base backtest configuration to optimize
base_config:
  data:
    symbols: ["SPY"]
    start_date: "2020-01-01"
    end_date: "2022-12-31"
    frequency: "1h"  # Hourly for more data points
    source: yahoo
  
  portfolio:
    initial_capital: 100000
    commission:
      type: fixed
      value: 1.0
  
  strategies:
    - name: ma_strategy
      type: moving_average_crossover
      # Parameters will be optimized

# Optimization configuration
optimization:
  method: bayesian  # Smart search, not brute force
  
  # Parameter search space
  parameter_space:
    fast_period:
      type: int
      min: 5
      max: 50
      step: 1
    
    slow_period:
      type: int
      min: 20
      max: 200
      step: 5
    
    ma_type:
      type: choice
      choices: ["SMA", "EMA", "WMA"]
    
    # Risk parameters can be optimized too
    stop_loss_pct:
      type: float
      min: 0.01
      max: 0.05
      step: 0.005
  
  # Constraints to ensure valid parameters
  constraints:
    - type: expression
      expression: "slow_period > fast_period + 10"
    - type: expression  
      expression: "fast_period >= 5"  # Minimum period
  
  # Multi-objective optimization
  objectives:
    - metric: sharpe_ratio
      direction: maximize
      weight: 0.5
    
    - metric: calmar_ratio  # Return/drawdown
      direction: maximize
      weight: 0.3
    
    - metric: win_rate
      direction: maximize
      weight: 0.2
  
  # Search configuration
  n_trials: 200  # Number of parameter combinations to try
  n_jobs: 4      # Parallel workers
  
  # Early stopping if no improvement
  early_stopping:
    enabled: true
    patience: 50  # Stop after 50 trials without improvement
    min_delta: 0.01  # Minimum improvement required

# Use all CPU cores for parallel execution
parallel: true
max_workers: 4

# Output best parameters and full results
output:
  save_all_results: false  # Only save top results
  save_top_n: 10
  export_path: results/optimization/