name: working_ensemble
data: SPY_5m

# Using the parameter_space format that the system expects
parameter_space:
  strategies:
    - type: keltner_bands
      param_overrides:
        period: 20
        multiplier: 1.5
        
    - type: bollinger_bands
      param_overrides:
        period: 11
        std_dev: 2.0