# Test configuration for Dual Momentum strategy
name: test_dual_momentum
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Dual momentum strategy (price and time-series momentum)
strategy:
  dual_momentum:
    params:
      lookback_period: 20
      momentum_threshold: 0.0

# Run with: python main.py --config config/indicators/momentum/test_dual_momentum.yaml --signal-generation --bars 100
