# Test configuration for Vortex Trend strategy
name: test_vortex_trend
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Vortex indicator trend reversal strategy
strategy:
  vortex_trend:
    params:
      vortex_period: 14
      crossover_threshold: 0.02  # Minimum VI spread for signal

# Run with: python main.py --config config/indicators/momentum/test_vortex_trend.yaml --signal-generation --bars 100

# Expected behavior:
# - VI+ (Vortex Indicator Positive): Upward price movement
# - VI- (Vortex Indicator Negative): Downward price movement
# - VI spread = VI+ - VI-
#
# - VI spread > 0.02: BUY signal (1) - VI+ dominant
# - VI spread < -0.02: SELL signal (-1) - VI- dominant
# - Between thresholds: No signal (0)

# Vortex indicators capture positive and negative trend
# movements within price bars. Crossovers between VI+ and VI-
# often signal trend reversals.