# Test configuration for Price Momentum strategy
name: test_price_momentum
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Price momentum strategy
strategy:
  price_momentum:
    params:
      lookback_period: 20
      momentum_threshold: 0.01  # 1% threshold

# Run with: python main.py --config config/indicators/momentum/test_price_momentum.yaml --signal-generation --bars 100
