# Test configuration for Momentum Breakout strategy
name: test_momentum_breakout
mode: signal_generation
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"

# Momentum breakout strategy
strategy:
  momentum_breakout:
    params:
      momentum_period: 10
      breakout_threshold: 0.02  # 2% momentum threshold

# Run with: python main.py --config config/indicators/momentum/test_momentum_breakout.yaml --signal-generation --bars 100

# Expected behavior:
# - Calculates rate of change over momentum_period bars
# - Momentum > 2%: BUY signal (1)
# - Momentum < -2%: SELL signal (-1)
# - Between thresholds: No signal (0)

# This is a trend-following strategy that enters positions
# when price momentum exceeds a threshold, indicating
# strong directional movement.