# Category-based wildcard optimization example
# This shows how to use wildcards for specific indicator categories
name: category_wildcard_optimization
mode: backtest
symbols: ["SPY"]
start_date: "2024-01-01"
end_date: "2024-01-31"
initial_capital: 100000

# Production strategy
strategy:
  rsi_bands:
    params:
      rsi_period: 14
      oversold: 30
      overbought: 70

# Parameter space for optimization (--optimize flag)
parameter_space:
  # Test specific indicator categories
  indicators:
    crossover: "*"          # All crossover strategies (sma_crossover, ema_crossover, etc.)
    momentum: ["rsi", "macd_crossover"]  # Specific momentum strategies
    volatility: "*"         # All volatility strategies (bollinger, keltner, etc.)
  
  # Test specific classifiers
  classifiers: [
    "trend_classifier",
    "volatility_classifier"
  ]

# Example usage:
# python main.py --config config/examples/category_wildcard_optimization.yaml --optimize

# This will discover and test:
# - All crossover strategies (10 strategies)
# - 2 specific momentum strategies
# - All volatility strategies (5 strategies)
# - 2 specific classifiers