name: keltner_top10_test
data: SPY_5m

# Top 10 performers from training, focusing on M=0.5 and exploring below
strategies:
  # Top 5 from training (all M=0.5)
  - name: kb_p22_m05
    type: keltner_bands
    params:
      period: 22
      multiplier: 0.5
      
  - name: kb_p21_m05
    type: keltner_bands
    params:
      period: 21
      multiplier: 0.5
      
  - name: kb_p26_m05
    type: keltner_bands
    params:
      period: 26
      multiplier: 0.5
      
  - name: kb_p23_m05
    type: keltner_bands
    params:
      period: 23
      multiplier: 0.5
      
  - name: kb_p25_m05
    type: keltner_bands
    params:
      period: 25
      multiplier: 0.5

  # Explore tighter bands (below 0.5)
  - name: kb_p22_m03
    type: keltner_bands
    params:
      period: 22
      multiplier: 0.3
      
  - name: kb_p22_m04
    type: keltner_bands
    params:
      period: 22
      multiplier: 0.4
      
  # Also test the sweet spot with even tighter
  - name: kb_p23_m03
    type: keltner_bands
    params:
      period: 23
      multiplier: 0.3

  # Include best M=1.0 performer for comparison
  - name: kb_p27_m10
    type: keltner_bands
    params:
      period: 27
      multiplier: 1.0
      
  # And one ultra-tight to see the limit
  - name: kb_p22_m02
    type: keltner_bands
    params:
      period: 22
      multiplier: 0.2