name: keltner_test_multiple_filters
data: SPY_5m
mode: exhaustive
strategy:
- keltner_bands:
    period:
    - 30
    multiplier:
    - 1.0
    filter:
    - null
    - volatility_above:
        threshold: 0.8
    - volatility_above:
        threshold: 1.1
