name: keltner_test_param_expansion
data: SPY_5m
mode: exhaustive
strategy:
- keltner_bands:
    period:
    - 30
    multiplier:
    - 1.0
    filter:
    - volatility_above:
        threshold:
        - 0.8
        - 1.0
        - 1.1
